### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#1]
- [x] Texts
- [x] Logos (sponsors, partners etc.)
- [x] Show only country specific logos

Text:
> The FIT Count is part of the Pollinator Monitoring Scheme (PoMS) within the UK Pollinator Monitoring and Research Partnership, co-ordinated by the Centre for Ecology & Hydrology (CEH). It is jointly funded by Defra, the Welsh and Scottish Governments, JNCC and project partners, including CEH, the Bumblebee Conservation Trust, Butterfly Conservation, British Trust for Ornithology, Hymettus, the University of Reading and University of Leeds.
PoMSaims to provide much-needed data on the state of the UK’s insect pollinators, especially wild bees and hoverflies, and the role they fulfil in supporting farming and wildlife.

> For further information about PoMSgo to: www.ceh.ac.uk/pollinator-monitoring to update

[PoMS logos.zip](https://github.com/NERC-CEH/fit-count-app/files/5844599/PoMS.logos.zip)

these shown when Cyprus is selected:

![PoMS-Ky](https://user-images.githubusercontent.com/7383162/105220847-333bcb00-5b50-11eb-80c0-c8e73d82824d.png)

![Darwin-logo](https://user-images.githubusercontent.com/7383162/105220875-3d5dc980-5b50-11eb-9f13-6d6c8611f52f.png)

**Comment by kazlauskis** [comment]
@kitenetter do you know where to find the sponsor logos?

**Comment by kitenetter** [comment]
@kazlauskis have emailed you

**Comment by Vilius-Stankaitis** [comment]
When Cyprus is selected should all logos appear or just those two?
