### ISSUE TITLE
Insect Group list

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#10]
* [x] list
* [x] thumbnail images
* [ ] species profile photos & annotations

**Example photos for honeybee species profile:** 
![Honeybee_1](https://user-images.githubusercontent.com/7383162/109025509-b227a480-76b6-11eb-88c2-b4bdc07119a5.jpg)

![Honeybee_2](https://user-images.githubusercontent.com/7383162/109025704-e00ce900-76b6-11eb-90bd-ac3a15ab6417.jpg)

**Example annotations**
Group | picture | Intro text | Caption 1 | Caption 2 | Caption 3 | Caption 4 | Caption 5 | Extra text
-- | -- | -- | -- | -- | -- | -- | -- | --
FIT Count group: Honeybees | Honeybee_1.jpg | Honeybees are larger than most   (not all) solitary bees, and smaller than most bumblebees. Look out for: | Long thin antennae, often angled   to form an ‘elbow’ shape | Eyes covering the sides of the   head | Hind legs broad and flattened | Abdomen can vary from mostly   dark to mostly orange | Long narrow cell in veins at   edge of wing |  
FIT Count group: Honeybees | Honeybee_2.jpg |   | Most of the honeybees you see   will be workers, which are female, and collect pollen into a moistened ball   on the outside of the hind legs |   |   |   |   | Male honeybees (drones) are   similar but have much larger eyes.

**Comment by kitenetter** [comment]
I think we can close this.
