### ISSUE TITLE
Timing of GPS fix vs Cyprus app release

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#100]
@kazlauskis please see my email to the Cyprus team with their Beta testing fixes and outstanding issues.

@kitenetter has received a couple of help emails in the PoMS account that suggest we need to get this GPS fix out ASAP. We only have until 30th September to keep counts coming in and then the UK FIT Count season closes (of course data can still be received).

Please let us know how much time is needed for the final changes for Cyprus and if we can possibly have both issues plus the Credits page change/s pushed to the app stores by end of this week?

**Comment by kazlauskis** [comment]
@CCarvell  We have finished working on the app right now. Shall we wait for the full credits list update or push it out with the Cyprus + GPS fixes only?

**Comment by kitenetter** [comment]
I'm working on the full credits list for the UK photos at the moment, will need another hour or so.

**Comment by CCarvell** [comment]
@kazlauskis thanks - did you implement those minor changes sent by Ioanna that were attached to my email last night?
@kitenetter thanks also - I will copy you in to the email with @JimChiazzese1 so that he is also aware of the UK photo credits to retain for LATAM countries.
@kitenetter and @kazlauskis do we need to put out a quick Tweet to Uk PoMS app users to alert them to update the app, or log out anad back in again to ensure they get the updated functionality?

**Comment by CCarvell** [comment]
@kazlauskis I am in meetings today so please can you notify the whole Cyprus team when you have pushed out the updates, and then again when you have app store approval?

@kitenetter and @BirenRathod it would also be good to check the FIT count website as per my email, for Greek translations and links to the app for Cyprus before it goes live - thanks

**Comment by kazlauskis** [comment]
OK. Yes, this update will include Cyprus text fixes from yesterday's email.

**Comment by kitenetter** [comment]
@kazlauskis for the Photo credits in the Cyprus version we need to add three names under the text "Thanks to the following for additional photos" - these names can be added at the end after the Cyrpus team names:

Gail Hampshire via Wikimedia
Malcolm Storey / BioImages
Trounce via Wikimedia

Let me know if you need any further information.

**Comment by kazlauskis** [comment]
Excellent, thanks!
