### ISSUE TITLE
Options for using the app for 1 km square FIT Counts

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#103]
Just wanted to capture some thoughts on this following discussion at the steering group for UK PoMS today.

In the UK we ask our 1 km square volunteers to carry out FIT Counts as part of the 1 km square surveys. Up until now we have treated these 1 km square FIT Counts as a separate dataset, to be distinguished from the public FIT Counts. Consequently, we have asked our 1 km surveyors not to use the app, because there is no way within the app of distinguishing between counts for the 1 km square survey and other counts.

However, the app is popular and the 1 km square surveyors would like to be able to use it! Options I can think of are:
1. Add a tick box to the app so that recorders can say "This is a 1 km square FIT Count" (will need to be country-specific)
2. Use the roles on the website to identify the recorders who are 1 km square surveyors
3. Use database queries to pull out all FIT Counts that are from the same combination of surveyor/date/1 km square as our pan-trap samples.

Those options have drawbacks: option 1 relies on people remembering to use the tick box (and also assumes that people will not use it when they shouldn't); option 2 will include FIT Counts that our volunteers do away from their 1 km square surveys; option 3 adds to the post-season data management workload (but is perhaps the best option?).

Questions:
- Is this also an issue for the EU scheme?
- Do we definitely need to continue treating the 1 km FIT Counts as a separate dataset?

**Comment by CCarvell** [comment]
@kitenetter of your 3 options, I think option 1 is the best from a user and data analysis perspective (some of our 1 km square surveyors will want to use the app outside of 1 km squares so 2 is risky; 3 seems fiddly for you/ the person with the database). Option 1 could be tricky from the app design perspective BUT based on your other questions:

a) Yes it could be an issue for the EU scheme, they will have fixed survey squares and may well want to do FIT Counts in those, but not currently a core element.
b) Yes I would like to distinguish counts on 1 km squares BUT also want to start analysing all counts within the same model. That way we can see if the 1 km counts are mirrored by the public counts (and pan traps) and vice versa, but also benefit from the extra power of the larger dataset.

One further thought: with the app we have (for now) lost the ability to accept photos of insects for potential verification, but with the website form we have retained that. I guess other countries won't have the insect species photo option if they only use the app, but it could be something to build into the app as phase 2 provided the infrastructure is there to deal with the extra photos?

**Comment by kitenetter** [comment]
For the UK 1 km square surveys we have now enabled this using the 'projects' feature. Not aware of any current demand to implement this elsewhere - closing.
