### ISSUE TITLE
How can we link users to country pollinator projects?

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#105]
FIT Count app users may be contributing to one of several country-based pollinator projects. On registration, they are asked if they wish to be contacted. But as far as I can see we have no way of knowing which country project they are associated with.

This means that if I want to contact all FIT Count app users who have contributed to the UK Pollinator Monitoring Scheme I have no easy way of doing so.

Do we need to add an option to the registration process so that users can say that they agree to be contacted and which project they are contributing to?

An alternative is to run a query to compare users to the location of their counts.

**Comment by kazlauskis** [comment]
We already ask which country the user belongs to in the app. This tailors the UX, i.e. different species lists, habitats but this setting is only stored in the device at the moment. What we could do is to also save this choice in the website so you could then use it when contacting users or analysing the data.

**Comment by kitenetter** [comment]
Ideally we want to be able to contact all people related to the country who have given permission to be contacted, regardless of whether they have yet submitted counts, so Karolis' suggestion sounds good.

**Comment by kitenetter** [comment]
Covered under #144 and #186 - closing.
