### ISSUE TITLE
Portuguese Demo app review results/issues 

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#109]
[corrections_Nov2021_JimNotes.docx](https://github.com/NERC-CEH/fit-count-app/files/7520416/corrections_Nov2021_JimNotes.docx)

@kazlauskis All the issues / comments from Brazil have been reviewed.
Where appropriate I have correct the master spreadsheet.
There are issues relating to the use of the term 'flower/floral visitor' in preference to 'insect' - these have been updated in the Portuguese in Transifex, but will need to be updated in the Brazil version English - I'm happy to do that if you can let me know where I'd make those changes.

Jim

**Comment by JimChiazzese1** [comment]
@CCarvell Just for your information Claire. The majority of the Brazil changes related to the need to change from 'insect' to 'flower visitors' so that it makes more sense in the bat/hummingbird context.

**Comment by kazlauskis** [comment]
@JimChiazzese1 thanks for the comments in the doc. I am splitting these up into multiple tickets for convenience.
