### ISSUE TITLE
Integrate with Indicia warehouse1

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#11]
Set up the warehouse to accept records from the app.

**Comment by kazlauskis** [comment]
@DavidRoy should we link to an existing iRecord POMS survey or should we create a new one?

**Comment by DavidRoy** [comment]
@kitenetter to confirm but I believe we are moving to a website for 'Pollinator Monitoring Scheme' (website_id = 136) and a survey for FIT Counts (survey_id = 636)

copying in @andrewvanbreda so he knows this too

**Comment by kazlauskis** [comment]
I can link the mobile app to use the POMS website survey `636` but this survey asks for some attributes which we don't directly capture during the survey - FIT Count project, Recorder type, Mailing list permission, Difficulty of survey... 

I wonder if it is not better to create an app-specific survey?

**Comment by andrewvanbreda** [comment]
Hi @kazlauskis 
Yes I think that is best, have an app specific survey. Have already assumed that would be the case.

**Comment by kazlauskis** [comment]
For reference, I have now created a new survey: `641`. It will share all the relevant attributes with the POMS survey.

**Comment by andrewvanbreda** [comment]
@kazlauskis Thanks Karolis, I have made a note of this ID in the website issue relating to this

**Comment by kazlauskis** [comment]
We are about to add other countries to the app which means that some of the shared survey attributes will have more options.  

@andrewvanbreda @kitenetter are you OK for us to add extra options to the habitat and flower attributes? These are shared, it might show up on the PoMS website too, no?

<img width="698" alt="Screenshot 2021-05-13 at 16 07 29" src="https://user-images.githubusercontent.com/7383162/118145417-7f639180-b405-11eb-948c-920fc255d2f1.png">

**Comment by kitenetter** [comment]
@kazlauskis do you mean that there will be additional attributes appearing in the dropdown lists on the PoMS website data entry form? If so that is highly undesirable, do we have any options for controlling which terms appear on the website?

**Comment by kazlauskis** [comment]
Probably, at the moment, the app and the PoMS website share the same Warehouse attributes. Andy knows more about what control he has when showing the forms on the website.

**Comment by kitenetter** [comment]
Does this also have any implications for the terms that appear in the app itself when used in the UK? We really don't want people to be able to select target flowers or habitats that are not on the UK list.

**Comment by kazlauskis** [comment]
No, in the app we have full control of which attributes will be shown to which users so this might only affect the website/reports.

**Comment by kitenetter** [comment]
Okay. In that case, we may need to set up a new set of terms for the PoMS website, so that it is independent of the app termlists - unless Andy can see a better option. I'm keen to minimise any additional demands on Andy's time as we have a lot to do in the next week, so let's see what the simplest option is. I'm worried that this will cause problems with the reports and with Welsh language handling that Andy has been working on.

@andrewvanbreda let me know how big an issue this is and whether you can see a simple solution - happy to help with setting up new terms/attributes in the warehouse if needed, but not sure what the other implications might be.

Tagging @CCarvell for info.

**Comment by andrewvanbreda** [comment]
@kitenetter @kazlauskis 
Sorry I got distracted by very a very urgent language issue today, so will look at what you have been writing about tomorrow

**Comment by andrewvanbreda** [comment]
@kitenetter @kazlauskis
Think am pretty confused what is going on to be honest.
If there are additional attributes in the app that won't appear on the website, this would be ok, apart from those attributes will not be available editing data from the app on the website. 
Also they must not be mandatory attributes.

What are these extra attributes?
Is it to do with countries and things?

If they are mandatory I would need to create new forms on the website and that is outside the original project spec.
I don't think I would be altering the forms to cope with those extra attributes at the stage if can be avoided.

If there are extra terms for the same attributes which are visible in the app but not the website then these would need to be hidden by jQuery.

Let me know

Thanks

**Comment by kazlauskis** [comment]
@andrewvanbreda this isn't new attributes, but existing attributes with extended options lists. So we basically need to add more select options to the habitats and flower attributes.

**Comment by andrewvanbreda** [comment]
@kazlauskis 
if you let me know which terms need hiding on the website, I will try to do that with jQuery.
I will need to know the exact ones to be excluded. Although there is the complication these would need to be shown when editing app data.

So I think what needs to happen is
1. Add them to the existing term lists on the website (including translation).
2. Let me know the ones you have added, and whether they need to be hidden on data added from the website.
(If it is ok to show them on the website, let me know the names of the new ones anyway so I can check the translation is working)

**Comment by kitenetter** [comment]
@andrewvanbreda there is no need to enable the additional terms to be edited via the PoMS website, as they will only apply to counts that are outside the UK. So if it is simpler just to hide them altogether on the website that should be fine.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Ok, so what need to happen is you to let me know which terms then once they have been added to the Warehouse.
I might be able to write an extension that can be added to each page to hide them.
There isn't a site wide option for this.

**Comment by kitenetter** [comment]
@kazlauskis please let us have the list of non-UK terms as soon as they are finalised

**Comment by kazlauskis** [comment]
Hi both, I think, it might be better to invert this and cheery-pick the UK specific options rather than the other way round. Otherwise, the list will most likely grow with every country we add to the project and you'll need to keep updating these terms on your website. My suggestion would be to eliminate any options that are non-UK related on the PoMS site.

An alternative to this would be for the app to use app-specific attributes instead. We have had a brief discussion around this and the conclusion was that in order to generate the reports on the website the app should use the same attributes.

**Comment by andrewvanbreda** [comment]
@kazlauskis 
I am not sure how terms would work like this though.
I suppose maybe I could tell the jQuery to use these, and always excluded everything else.
Yes maybe that would work.
I think specific app attributes is problematic, I would have to completely change the site.

I will see if I can get this to work within the budget.

**Comment by andrewvanbreda** [comment]
@kitenetter @kazlauskis 
Note I have just deployed jQuery code to the English/Welsh site that forces the terms on the 3 data entry forms to only show the existing terms. Any more added from this point won't show up.

Martin just sent me some terms for Cyprus, however the lists looked very different.
Initially the obvious answer is these should be just be new attributes with new lists.
But am wondering if that would cause trouble with the app.
If they need to be the same attribute/lists, someone will need to use similar jQuery to remove unwanted English/Welsh terms and deploy it to the Cyprus site. 
My jQuery can be used as a basis for that.

**Comment by kazlauskis** [comment]
Yes, from the app perspective, it is best to keep all the terms under same attributes. I agree that Cyprus or whatever other site will have to show country-specific terms only.

**Comment by andrewvanbreda** [comment]
@kazlauskis 
OK. No problem. Have advise Martin to add them to same list as the excluder has been deployed to the UK website.

**Comment by kitenetter** [comment]
@kazlauskis in the warehouse the UK target flowers are entered as a single text string with both English and scientific names, e.g.:
"White Dead-nettle - Lamium album"

In the Species_data spreadsheet you have just the English names in one column, with a separate column for scientific name.

When I add the Cyrpus targets to the warehouse, should I continue to use both English and scientific in one text string?

**Comment by kazlauskis** [comment]
I would probably follow the existing format in the warehouse. Whatever the format you choose, it will not impact the app. This is probably more for how the species will be rendered on the website and download reports.

**Comment by kitenetter** [comment]
Habitat and target flower terms now added to warehouse, updated spreadsheet supplied to Karolis.

**Comment by andrewvanbreda** [comment]
@kazlauskis @kitenetter 
The UKPoms site seems to be working fine (noticed a bug where welsh is bleeding through into the species grid attribute term list but that is unrelated, I will note that). So terms are indeed being excluded.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Note I have fixed the Welsh bleed through on the pan trap species grid mentioned in comment above.

**Comment by kazlauskis** [comment]
@kitenetter can this be closed now?

**Comment by kitenetter** [comment]
Closing.
