### ISSUE TITLE
Flies text is wrong

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#113]
> Flies the last text (extra text) is wrong (it was mistaken by a text on butterflies). The correct translation is on string #418 at Transifex. Jim: Correct on transifex, so looks like an import issue

![image](https://user-images.githubusercontent.com/7383162/141317025-398edd4b-0989-4834-973b-8dce18e56497.png)

@JimChiazzese1 what should this be?

![Screenshot 2021-11-11 at 16 33 01](https://user-images.githubusercontent.com/7383162/141317168-e93307ea-20dc-404c-b82d-bb3bab7e2671.png)

**Comment by JimChiazzese1** [comment]
Sorry - will need to check in on this again. When I initially looked it appeared that there was text from the butterfly guide appearing under the flies section, but I can't work out the error. will get back to you on this one

**Comment by JimChiazzese1** [comment]
Have reviewed.

What appears in the Portuguese version is;

As **borboletas** se alimentam de néctar e pólen, mas não coletam néctar e não têm cestas de pólen.

This translates as "Butterflies feed on...."

It should read;

As **moscas das flores** se alimentam de néctar e pólen, mas não coletam néctar e não têm escopa para carregar pólen.

Which is what actually appears on transifex. It is also correct on the spreadsheet.

**Comment by kazlauskis** [comment]
OK, this was just the matter of pulling in the new translations then.
