### ISSUE TITLE
Fix Brazilian credits page

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#115]
> Sentence in English - needs translation (“Ilustrações do aplicativo por:”) Last name needs correction: Paula Drago

![image](https://user-images.githubusercontent.com/7383162/141319444-97e22bb7-1fe9-477a-89ad-d21b84a7575e.png)

**Comment by kazlauskis** [comment]
@JimChiazzese1 can you confirm the credits page is OK now?

**Comment by JimChiazzese1** [comment]
@kazlauskis Yes, that looks all fine now
