### ISSUE TITLE
FIT Count donut graphics and need to exclude other countries from UK

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#117]
On the PoMS website donut graphics page we state:
"The charts are based on data from all FIT Counts submitted from the UK and Isle of Man, between 1 April and 30 September each year"
https://ukpoms.org.uk/flower-charts 
Two questions:
1. Can we check with Rich Burkmar, @kitenetter and Andy v-B that these FIT Count graphics have stopped updating as of end September, and are definitely filtering out non-UK counts on those target flowers?
2. Do we want to integrate country code into the code for generating the donuts so that we can offer them to present counts from Brazil, Chile, Arg and then Sweden etc on the FIT Count website? David has set up country pages not yet visible: https://fitcount.ceh.ac.uk/brazil 
We would need to add in the extra/ new target flowers and insect groups applicable to those countries.
OR should we offer Rich's code via GitHub for use by other country leads to apply as they choose?
@JimChiazzese1, David and I need to clarify our offering to the other countries asap.
I am also looking at how to discuss costs for 'ongoing maintenance and updates' in S America.

@burkmarr @DavidRoy @andrewvanbreda

**Comment by andrewvanbreda** [comment]
Hi @burkmarr @CCarvell

Richard did these so he will have to answer the questions on this as I simply don't know about their implementation.
What I can say is that on other areas of the site, the report code limits it to the UK as part of the report setup, so the graphs will need to do that themselves also (it isn't automatic)
I am happy to talk to Richard about this if needed.

**Comment by burkmarr** [comment]
The XML reports which serve the data for the charts are:

- https://github.com/BiologicalRecordsCentre/indicia-reports/blob/master/reports/projects/PoMS/poms-donuts-1.xml
- https://github.com/BiologicalRecordsCentre/indicia-reports/blob/master/reports/projects/PoMS/poms-donuts-1-my.xml

They inlcude these clauses to restrict records to those made between April and September inclusive:
```
and extract(month from cof.date_end) > 3
and extract(month from cof.date_end) < 10
```

This clause restricts the records to those that are made in IoM, NI, Wales, England and Scotland:
```
and array[214127, 1612, 1606, 1605, 1614] >> s.location_ids = true
```

**Comment by andrewvanbreda** [comment]
@burkmarr 
Hi Rich,
Thanks for the info here. It is useful to see this as then can spot any differences between what you are doing and myself.
One difference I have noted is with the locations.
The parameter I use on reports is this
intersect_location_ids=1605,1614,1606,1612,214127,203170,203169

So I have two extra locations, these are Jersey and Guernsey, so I think you need to include those unless you have been specifically told not to.
(unless I am wrong about that, although I discussed it with various people before implementing my reports).

@CCarvell I assume the reports on the website (i.e. everything that isn't Rich's graphics) shouldn't have a date restrictions, they don't currently have that other than the user selectable date filter, but there are no month restrictions on that.

**Comment by kitenetter** [comment]
@andrewvanbreda @burkmarr I think this is all fine as it stands. The website needs to allow for the collection of some data (e.g. for Channel Islands) that is not actually used for PoMS  analysis in the UK. And although we don't analyse data from outside the Apr-Sept period, we don't currently want to make it impossible for data to be submitted outside this period.

So the discrepancies between filtering on the website and filtering for the charts are correct and expected.

**Comment by kitenetter** [comment]
@kazlauskis I think this can be closed but I don't have permissions to do that - please can you give me suitable permissions, or just close it if you prefer.
