### ISSUE TITLE
Brazil Beta Ios issue

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#119]
@kazlauskis  Had this comment from Brazil, re: Brazil version of the app - "finally tested the beta version of the app for iPhone and it has not worked (it returns a message saying that "this beta version does not accept new users"). So we could not access the Brazil version, do you know if there is any problem?"

It still appears fine on android - is there a way of testing/confirming on ios?

**Comment by kazlauskis** [comment]
iOS Beta testing is only allowed for maximum 90 days, at that point we either need to release it or rebuild and issue a new Beta test.

**Comment by JimChiazzese1** [comment]
Thanks Karolis - What's involved in issuing a new Beta test on iOS? Do we need to make and report significant changes or can we just release a new version the same as the previous one, so that Brazil can test? Thanks

**Comment by JimChiazzese1** [comment]
As per email. I think we do the ireland work and release together.
