### ISSUE TITLE
Add Brazil and Ireland

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#120]

**Comment by kazlauskis** [comment]
@JimChiazzese1 Ireland is now in the [web demo app](https://fit.app.flumens.io/demo.html)

**Comment by JimChiazzese1** [comment]
Thanks Karolis, Just reviewed and there's a couple of things I've noticed:

- Orchid bees appear as an option on the fit count itself and the insect guide, and shouldn't be there (bee there...) 

- Habitat. There are three habitat categories that should appear differently in the Ireland version.

1. Upland moorland should appear as Upland bog/heath
2. Lowland heath should appear as Lowland bog/heath
3. Waste ground or brownfield site should appear as Waste ground

- Photo credits. Can we add the following under additional photo credits:
-photo credits are: Liam Lysaght, Colm Moriarty, John Walsh, Mary Douglas

Many thanks

Jim

**Comment by kazlauskis** [comment]
> Upland moorland should appear as Upland bog/heath
Lowland heath should appear as Lowland bog/heath
Waste ground or brownfield site should appear as Waste ground

Each habitat can have only one name. To change a name should be added to the main excel file as new rows. Ideally, this should be created as new entries in the Warehouse too but if the meaning is the same then you can just probably copy over the warehouse IDs from the similar habitats to these one.

**Comment by kazlauskis** [comment]
I've fixed the orchid bees now. The cell had some empty string inside and the script was just pulling this in as it contained some value, so I've made it to skip sheet cells with just empty spaces now.

**Comment by JimChiazzese1** [comment]
Thanks Karolis. I've now added the new habitats to the list, and referenced the same warehouse ID's. I'll double check with Martin if that will be fine, but think you're right. Thanks Jim

**Comment by kazlauskis** [comment]
As far as I understand, the Brazil is now done, is that right? We can then probably close the ticket and leave the Ireland #121  open.

**Comment by JimChiazzese1** [comment]
There's a flower image change to make, I'll review today and update the spreadsheet and content as necessary and let you know.

**Comment by JimChiazzese1** [comment]
Brazil just needed a couple of images changing. That's now done and uploaded, but waiting on the image credits.

**Comment by kazlauskis** [comment]
OK, thanks.
