### ISSUE TITLE
Ireland release to beta

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#122]
Ireland have reviewed the online demo and would like to proceed to beta. Thanks Jim

**Comment by kazlauskis** [comment]
The new Beta is now ready.

**Comment by JimChiazzese1** [comment]
Great - that's updated for me, but can you please remind me how a new user installs the beta? Thanks Jim

**Comment by kazlauskis** [comment]
Here are the links that should explain this to the users:
Android: https://flumens.notion.site/Android-app-Beta-testing-66b6f016ed624ee3adc1b7bd03063c3b
iOS: https://flumens.notion.site/iOS-app-Beta-testing-d66f1153f20b4f329d4cfe9fc82b6523

**Comment by JimChiazzese1** [comment]
Sorry Karolis. I think I meant how does a user find the beta url to install - When I uninstall and attempt to reinstall the FITCount from google play, it automatically brings up the FITCount Beta and knows I'm a beta tester, so assume that's due to cache of some sort.
If someone completely new is looking for the Beta test URLs - where do they find that? Apologies if I'm missing something completey obvious!

**Comment by kazlauskis** [comment]
Sorry! Yep, these are the links to join the Beta testing program:

* Android devices: https://play.google.com/apps/testing/uk.ac.ceh.fit
* iOS devices: https://testflight.apple.com/join/aVHilgCx

**Comment by JimChiazzese1** [comment]
Excellent - thanks Karolis.
