### ISSUE TITLE
Brazil - Text Change

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#123]
Hi @kazlauskis 
Brazil requested a text change to flower descriptions so that it was more appropriate for their users. Initially brazil requested a change to the English as well, but we've pushed back on this so the change is only to the Portuguese (actually I think we discussed this in email)

"spikes" to "long inflorescences" ("inflorescências compridas" in Portuguese) 
"flower heads" to "circular inflorescences" ("inflorescências circulares" in Portuguese).

Brazil have changed where they can in Transifex, but searching manually do not think they could find every instance. I have checked and from what I can see spike/spikes and flower head/heads have been updated.

Please can you verify if there is anywhere else these terms need to change, that may not be in Transifex and then we'll want to update the Beta. 
(As discussed, I think we can just update the online demo for review to make sure it's all sorted and then move to beta in the next round of updates - which will probably be adding Germany)

Cheers Jim

**Comment by kazlauskis** [comment]
The app shouldn't have any references to the flower type that aren't in the Transifex. 

As for the demo app update. I am not sure what you mean as we have moved past that and there already exists a Beta that people can install to their devices.

**Comment by JimChiazzese1** [comment]
Thanks Karolis. Regarding the demo app, I assumed everything was updated in there by default, so that it reflects everything that will go on to either beta or live, or do you have to maintain the demo app seperately?
I just mentioned that so the brazil team could check the terms now displayed as they needed, before the effort of uploading the Beta. In theory, as long as each instance of spikes and flower heads is updated then we're good to go. 
I've checked Transifex again and don't see any issue, so this change should be final. I'll check with Brazil and hopefully we can go straight live, rather than via another beta.

**Comment by kazlauskis** [comment]
No problem. Transifex changes don't automatically come to the demo app as we have to manually pull these in. I think, the flower type translations were done after we have pushed the app for Beta testing so it didn't make it to the public yet. We could update the translations and push these to the demo if you'd like? Then if these are OK we could release a new app version with the translations change alone to the public. Since there aren't any other features waiting in the pipeline for Beta testing this translations update would be straightforward.

**Comment by JimChiazzese1** [comment]
If we could update translations and push to demo that would be useful thanks. 
I didn't realise that Brazil was actually live, I thought it was only Beta? Out of interest, do you know if it's possible to have both the live and beta installed on the same device? Doesn't seem possible to download the public app from google play, it defaults to the beta.

**Comment by kazlauskis** [comment]
> Out of interest, do you know if it's possible to have both the live and beta installed on the same device? Doesn't seem possible to download the public app from google play, it defaults to the beta.

In general, no, you can't install different versions of the same app. Users can leave the Beta testing program to install live versions but by default, Beta users should get whatever is the latest version. 

> I didn't realise that Brazil was actually live, I thought it was only Beta?

Sorry for the confusion. Brazil was in Beta testing for a long time now and after we've added the Ireland to Beta and released it to live both countries went to the live app stores. In case we had multiple countries in Beta but you wanted to release only certain countries we could in theory push a special update just with those countries. Having said this, dealing with multiple pipelines could get rather messy. It is the best to keep the Beta testing of new features short-lived and frozen for adding new features until all the bugs are found and the Beta is released to the public.

**Comment by JimChiazzese1** [comment]
Got it! Makes perfect sense, we'll keep everythink on the demo online app, until country is completely satisfied with it and push to beta at an agreed time and for an agreed period, just long enough to test and have just one country in beta at a time. The S.American countries are a bit more of a challenge as they don't have an existing paper based FITCount already, so proving a bit harder for them to work out what they need. Thanks
