### ISSUE TITLE
Ireland go live

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#125]
Ireland have fully reviewed the beta and are happy to move this live now. I've not had confirmation from Ireland directly that the iOS issue with the count species text was fixed, but I see it was fixed from your side.
Can you let me know anything we need to know about going live, anything we need in place or timeline?
Thanks
Jim

**Comment by kazlauskis** [comment]
From my perspective, we can go live. The iOS issue is fixed but not in Beta yet, it will come out in the live release though. I can release it now and it should take up to 7 days (typically 2-3 days) for the app stores to review the app for the public release. 

@JimChiazzese1 should I release it then?

**Comment by JimChiazzese1** [comment]
Yes please. Let's release.
Thanks
Jim

**Comment by kazlauskis** [comment]
OK, I've pushed it for the public review now. It should come out shortly 🙂
