### ISSUE TITLE
Germany to online demo app

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#126]
I belive we have all the content now for Germany - please can you create the online demo app
Translation all appears complete
One single new species image added to the flumens folders, however the thumbnail folder won't let me upload the new thumbnail image, so that's attached here. 
Master spreadsheet all updated. 

![carpenterBee](https://user-images.githubusercontent.com/84846811/165763330-88ade0e9-98cb-4d0e-b563-247b1d4b0251.jpg)

Many thanks

Jim

**Comment by kazlauskis** [comment]
Thanks, I'll pick this up next week.

**Comment by kazlauskis** [comment]
@JimChiazzese1 

* I have added the new thumbnail
* Pulled in the latest data sheet 
* Pulled in the latest translations
* Fixed the Germany code from GR to DE
* Updated the app demo page

Looks like the German translators didn't quite follow the guidance. Some of the interfaces will be showing wrong in German because the tags (eg. <1>, <b> etc )were omitted in the translations.

**Comment by JimChiazzese1** [comment]
To clarify. When translating , the translator simply adds the numbers by clicking on the number/s in the english version on the top right and that will put the number in the correct place in their translation? I realise this is something I should have explained, but overlooked as everyone else did it without prompting previously.

**Comment by kazlauskis** [comment]
Yes, clicking on the number is the easiest. When you hover over it you can see the actual tags these numbers represent (e.g <1> or < i> ) that is behind it. Alternatively, the translator can just type in the tags in the translations too.

**Comment by JimChiazzese1** [comment]
Germany have now updated Transifex, so hopefully that's issue solved. Please can the updates translation content be pulled into the online demo. Thanks Jim

**Comment by JimChiazzese1** [comment]
After discussions with Germany and Chile about the use of verge, edge, stream and river – please can we change the habitat category 20086 from ‘verge along a stream or river’ to ‘Freshwater edge’.

Only Germany is currently actively using this target habitat.

I’ve updated this text in the spreadsheet already, please can you update on the demo app when you can.

**Comment by JimChiazzese1** [comment]
Sorry, should have added - the translation is Uferbereich von Flüssen, Bächen oder Seen - I can add this once Freshwater edge is in transifex

**Comment by kazlauskis** [comment]
All done 👍

**Comment by kazlauskis** [comment]
Btw, I've added the new German translation to Transifex.

**Comment by JimChiazzese1** [comment]
Thanks Karolis, afraid there was a spelling error/typo in the translation of Freshwater edge that crept in, I've not updated that on Transifex. (It's Uferbereich von Flüssen, Bächen oder Seen, but was showing as Ferbereich von Flüssen, Bächen oder Seen.
Also, for carpenter bee, the text and image is missing from both the german and english versions of the insect guide - looks ok in transifex, might just have not been picked up from the spreadsheet when importing. 
Thanks Jim

**Comment by kazlauskis** [comment]
done
