### ISSUE TITLE
Ireland live app not opening

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#127]
Just had this comment from Ireland:

_I just tried to install. It seems to install but won’t open? You get a blank screen. I had someone else check who wasn’t involved in beta testing and she has the same issue. We’re both on android_

**Comment by kazlauskis** [comment]
I cannot reproduce this yet. What is their Android system version? Does reinstalling the app help?

**Comment by JimChiazzese1** [comment]
Android 12 in both cases. Have tried uninstall and reinstall but same issue.

**Comment by kazlauskis** [comment]
@JimChiazzese1 there was indeed an issue for the Android 11/12 devices. I have now fixed it and pushed an update v1.1.1. It should come out shortly.

**Comment by JimChiazzese1** [comment]
excellent - thanks Karolis. Will let you know when Ireland verify all good.
