### ISSUE TITLE
Chile spreadsheet content to transifex

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#128]
Chile content is updated on the spreadsheet, please can this be moved to Transifex for translation.

**Comment by kazlauskis** [comment]
This is done now.

**Comment by JimChiazzese1** [comment]
Thanks Karolis. Can you remind me about the tagging of country content in Transifex. I remember you had a work around/solution so that a country would only see the text being used in their version of the app to prevent them needless translating content they don't need. Can you share details of how a coutry achieves that please. 
Thanks
Jim

**Comment by kazlauskis** [comment]
@JimChiazzese1 Here you go https://flumens.notion.site/Filtering-translations-6275210fbcb94ab5a53413a1a31cd833
