### ISSUE TITLE
FITCount camera use on android 12

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#129]
Testing the app (here and Ireland) and unable to directly open the camera to take a photo from the prompt on the app.
Apologies, but I'm not aware if that was always the case or if this is a new issue on android 12. 
Should we be able to click through from the app or can we only upload gallery images to a count?
If the latter, we'd probably need to update the text so users know to take an image first.

(the uploading of an image from the gallery remains unaffected)

Apologies for all the bugging, but seems Ireland are at least testing the app rigourously. 

![Screenshot_20220504-191317](https://user-images.githubusercontent.com/84846811/166886096-b2d1f024-456c-4458-afe1-67cb9ff507a7.png)

**Comment by kazlauskis** [comment]
Thanks, I'll look into this.

**Comment by kazlauskis** [comment]
It is fixed now and will come out in v1.1.2 shortly.
