### ISSUE TITLE
FITCount online demo not working

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#131]
https://fit.app.flumens.io/demo.html is currently giving the follow error code

404: NOT_FOUND
Code: NOT_FOUND
ID: lhr1::9m68n-1652276640075-acbbbadf7cc5

**Comment by kazlauskis** [comment]
Yeah, there was some change to the hosting provider's settings. I'll fix it asap.

**Comment by kazlauskis** [comment]
That's done now.
