### ISSUE TITLE
Germany demo app updates

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#132]
Changes to the Germany FITCount demo.

- "Blütenreiche Wiesen und Weiden" (Grassland with wild flowers) was incorrect in transifex (lower case b) - this have now been updated in transifex.

- Extra space and full stop was in Transifex ( .Die App wird Dir mitteilen,) - this has now been updated in transifex
- Information page, change "http://ukpoms.org.uk/fit-counts" for https://www.ufz.de/spring-pollination/index.php?de=49254
- Add 'Thomas Schmitt' to Germany photo credits

There may be one further change, it's currrently being debated, so will update when decision reached. 

Thanks

Jim

**Comment by DavidRoy** [comment]
@JimChiazzese1 is that the right link?  Shouldn’t it be a link to the Ireland website not the ufz spring one?

**Comment by JimChiazzese1** [comment]
Sorry if that wasn't clear, when I said appear _under_ 'the all-ireland pollinator plan' - I meant physically appearing underneath as a new link, rather than linking to that text.
The new line will be the text EU-Projekt SPRING linking to the UFZ site www.ufz.de/spring-pollination/index.php?en=49053

**Comment by kazlauskis** [comment]
Done.
