### ISSUE TITLE
FIT Count app observations not uploading

### ISSUE THREAD

**Issue by larspett** [NERC-CEH/fit-count-app#134]
Hi,
Some of my volunteers in the mountains have problems uploading FITCount app data from June 10th. They have tried repeatedly and it doesn’t upload. I asked if the app was up to date and it should be, but one never knows… The user is "Leif Björk" and he has tried several times but doesn't want to restart the app in case the data is lost. Can you see if the data has been added to Indicia or if it still is waiting? Have there been any similar issues lately? The 4G coverage should be ok in that area (Merkinäs).

<img width="1062" alt="Screenshot 2022-06-13 at 10 14 42" src="https://user-images.githubusercontent.com/19598308/173309928-16dcc903-b8bf-4fed-8360-ae321538d745.png">

**Comment by kazlauskis** [comment]
Hi, can you please send me the app version number and the exact time of an unsuccessful upload? I will then check our server logs.

Logout and login might help in this case. Restarting the app shouldn't loose any records.

**Comment by larspett** [comment]
The  version is 1.1.3 build 144, he tried most recently at 11:21 CET (daylight savings time)

**Comment by kazlauskis** [comment]
Thanks. This user should logout (uncheck "Discard local data" when prompted) and login back again. I think this should fix the upload issue.

**Comment by larspett** [comment]
OK will check and confirm

**Comment by kazlauskis** [comment]
@larspett Is this still an issue?
