### ISSUE TITLE
Germany translation fix and move to beta

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#136]
Hi Karolis, 
Some more minor tweaks to the translation - see attached. Issues 2-6 have been changed in Transifex.
Issue 1 seems to have crept in when pulling in translation to the online demo (it's 'und' on transifex but appears as 'Und' on the demo app)
[Korrektur 6.22.pdf](https://github.com/NERC-CEH/fit-count-app/files/8909460/Korrektur.6.22.pdf)

Once these issues are updated please can we push to beta - Germany have a team ready to test.

Jim

**Comment by kazlauskis** [comment]
This is done now. App stores are still reviewing the new Beta build, which might take another day.
