### ISSUE TITLE
Possible cause for some upload problems

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#137]
We are continuing to get reports of difficulties registering and uploading records. Richard Dawson has looked into this further and has unearthed some issues (that arose on iOS devices) that I have been able to replicate on Android.

When a user who first registers via the app, they are asked for an email address and their full name. Registration cannot be completed without providing these. The account then needs to be verified via an email. If a user does that successfully, they are shown this screen:

![image](https://user-images.githubusercontent.com/16039111/178319179-c0970c81-9065-48eb-8204-7a2e9eebf34e.png)

That has a message about setting "at least your last name on your user account". However, it is not very obvious how that should be done, nor is it at all obvious WHY it should be done, given that the user has already provided a full name.

It is possible to continue at this point without adding the first name or last name, and going on to use the app for a FIT Count. If the user does that, the count results fail to upload, and no error message is given to explain to the user that anything has gone wrong.

Questions:
1. Do we really have to ask the user to provide a "full name" AND a "first name/last name" combination, or can we remove one or other of those options?
2. If we do have to have first/last name, can we ask the user to provide this as part of the main registration process, rather than having to do it as a separate step?
3. If it does have to be a separate step, I think we need to give more explanation to the user about how to do so.

The process of editing the user account is very cumbersome, especially when accessed via a phone, and I will add a separate issue for that.

**Comment by kazlauskis** [comment]
You should be able to upload records right after clicking that verification link. Isn't that the case?

**Comment by kitenetter** [comment]
There is an increasing number of messages in the PoMS inbox from people who are unable to upload FIT Counts, all of which (so far) seem to be related to missing first and last names.

I think this must be a new problem? I don't recall it causing difficulties in the past.
