### ISSUE TITLE
Editing user account is very cumbersome and includes unnecessary information

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#138]
Following on from #137 if a user does try to edit their account to add a first and last name, it is a very cumbersome process, especially if done on a small-screen device. I'm not sure if this is an issue related to the app or to the website (and the underlying Indicia infrastructure) - I think it is probably the latter.

Most importantly, the user if faced with a very long list of "Species groups", which are irrelevant to the FIT Count, and take up a huge amount of space. Can we remove this section altogether? I assume it was just left there as a default from the iRecod account infrastructure.

Other elements that are not relevant to a user who is simply trying to register their account are:
- Picture
- Contact settings
- Time zone

Given that it appears we have to have the first name and last name filled in in order for counts to be uploaded, it would be good if the first and last name were at the top of the page for ease of access (unless we can include this in the app registration process itself, which would be even better, see #137)

(I've tagged this to Karolis but I think it might need to be an issue for Andy, and I can't see him on the list of assignees.)

**Comment by kazlauskis** [comment]
Tagging @andrewvanbreda 🙂

**Comment by andrewvanbreda** [comment]
@kazlauskis @kitenetter 
Yes I will look into this.

**Comment by andrewvanbreda** [comment]
@kazlauskis @kitenetter 
I have made the requested changes, but not the ones about the name fields being added to app registration.

Some other possible oddities?
1. Do we want them to set Google Analytics
2. The contact checkbox has the label "I allow to be contacted", seems like a slightly odd way of writing this
UKPoMS says "Are you happy to be contacted?"
3. There is a Full Name field, not sure other projects use that.

**Comment by DavidRoy** [comment]
1. Not needed as this is covered by the privacy notice.  We do not allow opt in/out
2. Agreed
3. I support simplification on this

**Comment by BirenRathod** [comment]
@andrewvanbreda Is this for ukpoms.org.uk website or fitcount.ceh.ac.uk?

**Comment by BirenRathod** [comment]
@andrewvanbreda 
> 1. Google analytics tick box - I'm not aware that we need it but I don't know what it does.
Is this for ukpoms.org.uk or fitcount.ceh.ac.uk?

**Comment by kitenetter** [comment]
@BirenRathod this is for fitcount.ceh.ac.uk

**Comment by BirenRathod** [comment]
Thanks @kitenetter. I have hidden that field now. It will help to track if there is an unusal activity happened.

**Comment by andrewvanbreda** [comment]
@kitenetter @DavidRoy @BirenRathod 
Have changed the label on the contact checkbox
Awaiting response from Karolis before taking any action regarding Full Name.

Martin
Was the account page always like this, or did it recently start becoming messy?

**Comment by kitenetter** [comment]
@andrewvanbreda I'm not sure - we've had issues with the missing first name/last name for the last month or so, and I don't recall this being a problem before, but I can't be certain when or if things have changed. I don't recall seeing the long list of species groups when dealing with user accounts in the past, but I'm also aware that my memory is unreliable :)

**Comment by andrewvanbreda** [comment]
@kitenetter 
There is a possibility that things changed when the site was updated for anonymisation, as other bugs in the Indicia Easy Login module were also fixed at same time.
This can sometimes cause things to appear to go wrong even though the code is actually technically working better (for instance something might appear if it was incorrectly not showing before).
I don't know that happened in this case, but it is possible this is the cause.

**Comment by andrewvanbreda** [comment]
Hi @kitenetter
Please close this issue if you are happy now, as realised I don't have rights to close. 
(The Full Name part of this issue is now being dealt with elsewhere. The First Name and Last Name were automatically installed by Indicia's Easy Login module. These have been removed with a workaround, and a permanent fix using a cutdown Easy Login module has been coded ,and will be put live as part of another Github issue. You will not notice notice any difference when this happens but just provides a more elegant fix.
https://github.com/NERC-CEH/fit-count-app/issues/141)
Cheers.

**Comment by kitenetter** [comment]
Thanks @andrewvanbreda - closing.
