### ISSUE TITLE
Add onboarding screen texts

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#14]
What images and texts to use?

**Comment by kazlauskis** [comment]
@CCarvell have you had a chance to think about what you'd like to say in the app onboarding screens? some examples below:

![image](https://user-images.githubusercontent.com/7383162/110782195-bfb85f00-825e-11eb-8bed-00de5e11ff8c.png)
![image](https://user-images.githubusercontent.com/7383162/110782206-c34be600-825e-11eb-8962-f50d8b9ff149.png)
![image](https://user-images.githubusercontent.com/7383162/110782225-c8109a00-825e-11eb-83ce-b228e5f95fad.png)
![image](https://user-images.githubusercontent.com/7383162/110782243-cc3cb780-825e-11eb-870b-e776f11143e4.png)

**Comment by kitenetter** [comment]
Here are mock-ups of two onboarding pages.

@CCarvell please confirm you are happy with the content
@kazlauskis please confirm that this looks practical to implement

I will then send photo and text.

![Splash 1](https://user-images.githubusercontent.com/16039111/110835671-01fd9280-8297-11eb-9adc-74ad268b80d8.png)

![Splash 2](https://user-images.githubusercontent.com/16039111/110835691-075add00-8297-11eb-9d04-6b55b99cefc9.png)

**Comment by CCarvell** [comment]
Brilliant! Happy to approve with one minor edit:
"check out the insect ID guide" rather than pollinator?

**Comment by kazlauskis** [comment]
Thanks, that looks good.

**Comment by kitenetter** [comment]
@CCarvell I was trying to be 'international' and refer to pollinators rather than insects, but it is difficult to be consistent about this in the context of the FIT Count, and I've used "insects" in point 4. I will change "pollinators" to "insects".

**Comment by CCarvell** [comment]
This it tricky - as it got me thinking that we don't really make it clear in the ID guide that spiders and other non-insect flower visitors for UKPoMS are not to be included. 
Let's make it fit for purpose for UK, Cyprus and rest of EU will probably also stick with insects (rather than birds and bats etc being added) and we can review phrasing for the S American version later.

**Comment by kitenetter** [comment]
Text and photos:

[onboarding.zip](https://github.com/NERC-CEH/fit-count-app/files/6125362/onboarding.zip)

(The photo is the original and will need cropping.)

**Comment by Vilius-Stankaitis** [comment]
minor changes, is it okay?

![Screenshot 2021-03-12 at 11.22.59.png](https://zube.io/files/nerc-ceh/1272abf4e0b2cf77b590f58a601a8ef6-screenshot-2021-03-12-at-11-22-59.png)

![Screenshot 2021-03-12 at 11.22.53.png](https://zube.io/files/nerc-ceh/51789e584b63cf2c7772bdc9e1776a17-screenshot-2021-03-12-at-11-22-53.png)

**Comment by kitenetter** [comment]
Typo: the word "Count" should not appear at the end of bullet point 2.

Otherwise looks great!
