### ISSUE TITLE
Germany beta fixes

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#140]
Some minor changes to the Germany version. Most issues are correct on transifex and correctly imported, but after further review the translation does not work exactly so request is to change the text. Details are attached, the changes have been made in transifex
[FIT-Count_Beta_last corrections.docx](https://github.com/NERC-CEH/fit-count-app/files/9110276/FIT-Count_Beta_last.corrections.docx)

There is one issue regarding the survey start button (ERFASSUNG STARTEN) - I've asked for futher clarification on this as it appears fine for me (android)

**Comment by JimChiazzese1** [comment]
Can confirm the ERFASSUNG STARTEN is an Apple issue.
![photo_2022-07-07_11-58-13](https://user-images.githubusercontent.com/84846811/178946781-965e1205-aab5-4d69-9f71-6bc5df43fdea.jpg)

**Comment by JimChiazzese1** [comment]
That's right. 
Does make me wonder if Germany didn't check their translations very carefully when initially doing it or if they're just more focussed than other countries. Cheers

**Comment by kazlauskis** [comment]
No problem, I'll update the app and push it to the public app stores now.

**Comment by JimChiazzese1** [comment]
Great. Thanks - from memory that should auto-update for most users shouldn't it?

**Comment by kazlauskis** [comment]
The iOS German release was indeed rejected because of the lack of the account delete option. #142

**Comment by JimChiazzese1** [comment]
Thanks Karolis. Is there a timeline for the release of the account delete option? JUst back from a week away so catching up, apologies if this is covered in an email thread I've yet to get to. Jim

**Comment by kazlauskis** [comment]
In short, this depends on how much we want to test the new app version. The longer answer I've sent to this over the email now 🙂
