### ISSUE TITLE
Portugal to Transifex

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#143]
Portugal are planning to start on the FITCount app shortly. In theory much of the Brazilian translation should work for Brazil. Is it possible to set up Portugal on Transifex and also duplicate all the Brazilian (Portuguese) translations for the interface aspects of the FITCount. They can then edit as necessary and we can update with the species specific content when that's developed. Many thanks Jim

**Comment by kazlauskis** [comment]
Done now. I've split the current Portuguese into two:

<img width="1033" alt="Screenshot 2022-07-22 at 12 49 08" src="https://user-images.githubusercontent.com/7383162/180434054-d59b6107-d0a8-4ef9-a0c4-260cf3ab4df4.png">
