### ISSUE TITLE
Chile flower change

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#146]
Chile would like to change the local language (Spanish, Chile only) of Fuschia to Chilco.
It does not need to change on the Chile English version, just the Chile Spanish, as it's the more common name locally. 
However, when I search for Fuschia on Transifex it doesn't seem to appear in the Spanish, so not sure how we change this on Transifex?

**Comment by kazlauskis** [comment]
You can find this plant under the Fuchsia name. It is already translated as Chilco in Transifex, so I have pulled in the new translations and updated the demo web app.
