### ISSUE TITLE
FITCount Brazil app camera issue

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#150]
Brazil have reported the following issue, but I am unable to replicate it on android on the live app. To me it sounds like it might be related to setting permissons for the app to use the camera, which may be different on iOS vs Android. Currently waiting for confirmation from Brazil about which platform they're on. 

"I tried to take a photo with the camera, but using this option the app shut down/started again at "start survey"... It only worked using a photo from the gallery."

**Comment by kazlauskis** [comment]
What is the device?

If the device has less than 4GB of RAM then it can't handle the camera app and the FIT apps together in the background.

**Comment by JimChiazzese1** [comment]
It's confirmed as android. I have no problem on my android, so will see if they're able to review the RAM on their device

**Comment by JimChiazzese1** [comment]
Motorola G7 Play, apparently has only 2gb of RAM, so would account for the issue. However, this is a 2019 phone, so not ancient really. Which means quite a few users may experience the same issue. If it's likely to be widespread we probably need to add a warning message or information of some sort?

**Comment by kazlauskis** [comment]
It's an issue that has cropped up in some other projects too but, in general, it is a rare case and we haven't done anything about it in the past. Users with such low-end devices will experience the same issue with a number of other apps too so some will know this limitation already. 

Ideally, we would show a warning in the app when the device has little RAM but there isn't an easy way to check for the available memory from the app. We can exclude the app from certain devices but this would be a tedious task keeping track of each device specification. If this issue comes affects more people then maybe we could specify the minimum requirements somewhere instead, what do you think?

**Comment by JimChiazzese1** [comment]
Adding Claire to this for her thoughts @CCarvell - I have no idea if this is likely to be a more common issue in S.America vs EU countries. 
If it's a rare case then I don't think we need to go as far as the second suggestion, but adding minimum requirements text seems a simple solution and gives the opportunity to explain the workaround (eg upload photo from gallery)

**Comment by kazlauskis** [comment]
I agree, most of our other apps contain a "Help" page that explains how the app works, or its limitations.

**Comment by JimChiazzese1** [comment]
Do you have a sample you can share that we can modify to suit the FITCount?

**Comment by kazlauskis** [comment]
Yeah, maybe the [FAQ in this one](https://irecord-butterflies.app.flumens.io/demo.html)?

**Comment by JimChiazzese1** [comment]
I think a comprehensive FAQ/How to page for the app will be a good idea in due course. Another thing for an country coordinators working group, once we get to that point. In the more immediate term, I was just thinking about a system requirements type note just to cover off the issue of the 2gb RAM. I didn't see anything similar on the butterflies app, but suspect you were sharing an idea of where we could put that type of content?

**Comment by kazlauskis** [comment]
Yes, that's right. We haven't put the minimal requirements section in any other project yet. But that might be because other projects focus on European users with more powerful phones, just a guess.

**Comment by kitenetter** [comment]
Not clear if any action still required - closing for now.
