### ISSUE TITLE
Missing flower images 

### ISSUE THREAD

**Issue by Vilius-Stankaitis** [NERC-CEH/fit-count-app#153]
Hello, 

Would be possible to get flower images? Currently missing:

- Blueberry
- Cowberry
- Geranium
- Devil's-bit Scabious/Field Scabious
- Brown knapweed/Greater knapweed
- European goldenrod
- Rosebay willowherb
- Red clover/Zigzag clover
- Leontodon, Picris, Hypochaeris and others
- Hogweed/wild angelica/garden angelica

Also, in the species guide page "Other wasps" species option exist, but the text in the "Other Insects" says 

"This category is for any insects that don’t fit into the other insect groups, and can also be used for any insects that you can’t identify into a group at all. Please count all the insects you see, and use “other insects” for any that you don’t recognise. For example, **solitary wasps**, **parasitic wasps** and sawflies are counted as “other insects”. Sawflies are related to bees and wasps but there are a number of differences."

Is it a mistake?

**Comment by kitenetter** [comment]
I have photos of a few of those plants, see links below. I make no claims for the photos being especially good and I'm sure better alternatives could be found via wiki or flickr creative commons.

I remember being told that there had been some discussion over how to categorise wasps for SPRING but I don't know what decisions were made.

Field Scabious:
https://1drv.ms/u/s!Ak5pqPfqMN7VgdJFXB894KYn-DF_uA?e=Gqm15y

Greater Knapweed:
https://1drv.ms/u/s!Ak5pqPfqMN7VgdNov0yaQ3T2NILE5w?e=gfmfOw
https://1drv.ms/u/s!Ak5pqPfqMN7Vgf5NESy3VcI__5jSww?e=dF2hS9

Leontodon hispidus:
https://1drv.ms/u/s!Ak5pqPfqMN7VgdI23V6DjhCTJYr0Dw?e=4FtFQ4

Hogweed:
https://1drv.ms/u/s!Ak5pqPfqMN7Vhd4JUtJsEoenU8kTrA?e=qdYrxM
https://1drv.ms/u/s!Ak5pqPfqMN7Vhd5L0FYDoARrPT54Iw?e=HsSE5n
https://1drv.ms/u/s!Ak5pqPfqMN7Vhd5c1fNBaanXufO9rQ?e=dTM52W

**Comment by DavidRoy** [comment]
@kitenetter you could also ask @sacrovert if it's possible to use the photos used for the forthcoming online plant atlas.  I 'think' we are ok to use these in general
