### ISSUE TITLE
Croatia FITCount - update text and go live

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#161]
Croatia have now finished full review on the online demo app. They have updated some of their translations to better instruct the user instructions. Please can the updated text from Transifex be pulled in and the app made live. However, if you think we should have an interim review of the updated text in the online demo before live, then happy to push back on this. Thanks

**Comment by kazlauskis** [comment]
OK, will do that this week.

**Comment by JimChiazzese1** [comment]
![FITCount_Android_9May23](https://user-images.githubusercontent.com/84846811/237036460-c7adb23a-d9cd-42a3-9b85-7cf99b5a09b0.png)

@kazlauskis Hi Karolis - Croatia is content on the App all seems to be there, but Croatian language option is missing for me on Android, see attached screenshot. Have updated app via app store etc. 

Noticed one other minor issue - Rock-roses appears in the spreadsheet, where it should probably be Rock roses. I've updated in the spreadsheet, so assume that change will push through to the live app next time there's an update/push live of any content? Thanks Jim

**Comment by kazlauskis** [comment]
Oops, sorry! I am fixing this right now 😉
