### ISSUE TITLE
FITCount App Map default for non-UK countries

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#162]
Currently the app defaults to the UK map view before locating the user GPS on the correct location.
This may really only be an issue with the online demo on the device - if that is the case then probably not necessary to persue, however if issue on the live app then could we resolve with the use of country specfic map please.
Interested to know if this is really something a user would only see on the first/initial use of the online demo or the app? If, after initial use, the app shows last cached map view then probably don't need to adjust.
Thanks

**Comment by kazlauskis** [comment]
@Vilius-Stankaitis 
- [ ] change the map to Mapbox vectors.
- [ ] centre to the currently selected country.

**Comment by kitenetter** [comment]
This appears to be completed? Closing.
