### ISSUE TITLE
FITCount app - broken SPRING link

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#163]
The EU-Project SPRING link on the 'About' page of the app is broken. This goes to a 'web page not available' page on Android that cannot be closed/go back, so the app has to be closed and re-started.

@CCarvell Please can you confirm what the correct link should be. Should it be - https://www.ufz.de/spring-pollination/ ?

Jim

**Comment by kazlauskis** [comment]
Thanks, I'll fix it.

**Comment by DavidRoy** [comment]
That's the right SPRING link, thanks
