### ISSUE TITLE
FITCount app - Croatia - Broken links

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#164]
The Privacy and Terms links on the Menu for Croatia are broken. At this stage they should link to the English Privacy/Terms as per the other countries. 
Thanks
Jim

**Comment by kazlauskis** [comment]
It would be better to fix this one on the website instead. I remember, initially, country partners were also translating these website documents (e.g. [CY](https://fitcount.ceh.ac.uk/cy/terms), [EL](https://fitcount.ceh.ac.uk/el/privacy-notice)) but if some aren't doing that anymore, then you could place a redirect to the English version on the website until the translations are done. 

All the document links from the app follow this pattern:
 https://fitcount.ceh.ac.uk/LANGUAGE_CODE/terms
https://fitcount.ceh.ac.uk/LANGUAGE_CODE/privacy-notice

**Comment by kitenetter** [comment]
@JimChiazzese1 happy to help if I can, but I don't really understand how the language translations work on the website, and I'm not sure what needs to be done to duplicate the English versions. If @andrewvanbreda can talk me through it that would be good.

**Comment by BirenRathod** [comment]
@kitenetter I can help you with this as @andrewvanbreda is busy.

**Comment by JimChiazzese1** [comment]
Thanks @kitenetter and @BirenRathod - That would be great. At this stage it's just duplication of the English language Terms and Privacy, but on the links as per Karolis' message. For Croatia the country code is HR.
