### ISSUE TITLE
FITCount App - Chile to Live

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#165]
Hi Karolis,
Chile have reviewed thoroughly and are happy to move live.
As with Croatia, I assume we should copy the existing english terms/conditions to the URLs below for Chile?

- [x] App
- [ ] #167
https://fitcount.ceh.ac.uk/es/terms
https://fitcount.ceh.ac.uk/es/privacy-notice

Thanks
Jim

**Comment by kazlauskis** [comment]
Thanks, I'll work on this next week then 👍

**Comment by kazlauskis** [comment]
I've done my bit now. Someone should still add the Spanish website pages.

**Comment by JimChiazzese1** [comment]
Thanks @kazlauskis - Although Spanish website pages we'll need pages for Chile rather than Spanish, as Spain will also be joining and potentially have different translations/information on their pages, so i'll request Biren creates:
https://fitcount.ceh.ac.uk/cl/terms
https://fitcount.ceh.ac.uk/cl/privacy-notice

Thanks

**Comment by JimChiazzese1** [comment]
Sorry @kazlauskis - That should of read "_should_ we request Biren creates....."  What are your thoughts on this. We'll need to seperate Chile Spanish from Spanish Spanish at some point, the same as we have we Portuguese. What do you suggest?

**Comment by kazlauskis** [comment]
At the moment, the links are generated using the IETF language [codes](https://www.venea.net/web/culture_code), this actually directly comes directly from Transifex. It's essentially `language`+`region`, like `en` (whole world), `pt-BR` (Brazil), `pt-PT` (Portugal). So let's create `es-CL` for Chile, then.

**Comment by DavidRoy** [comment]
Agreed. This is how Drupal will work too

**Comment by JimChiazzese1** [comment]
Hi @kazlauskis - Biren created the pages below with the duplicated UK terms/privacy
https://fitcount.ceh.ac.uk/es-CL/terms
https://fitcount.ceh.ac.uk/es-CL/privacy-notice
These will need updating on the app

**Comment by kazlauskis** [comment]
This is done in the app. For some reason, the website links point to missing pages for me.

**Comment by BirenRathod** [comment]
@kazlauskis you need to use lowercase for Chile like es-cl in the link.

**Comment by kazlauskis** [comment]
@BirenRathod Is this for Chile only, or do you use lowercase codes for every country?
