### ISSUE TITLE
FITCount page duplication for Croatia and Chile

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#166]
Hi,
As per the thread on the Croatia broken link issue, are you happy to create the duplicate privacy and terms pages for Croatia...we also have Chile going live soon, so would need pages for them also.
At this stage we're just duplicating the english language terms and privacy notice, prior to posting up the translated versions.

For Croatia links should be:
https://fitcount.ceh.ac.uk/hr/terms
https://fitcount.ceh.ac.uk/hr/privacy-notice

For Chile links should be:
https://fitcount.ceh.ac.uk/cl/terms
https://fitcount.ceh.ac.uk/cl/privacy-notice

Many thanks

Jim

**Comment by BirenRathod** [comment]
@JimChiazzese1 I have added both languages. Chile doesn't have a flag at present but that will be added later on. 
Also, I noticed that there is no privacy page created in English due to I can't able to create that page in Croatia and Chile. Not sure who is going to add that but whoever is going to add, it will be good to add pages for Croatia & Chile as well.

**Comment by BirenRathod** [comment]
@kitenetter I have also added the translation for the footer block, so the links should be available in those languages. 
When I mentioned translation added means not actual content translated like those links still show in English language.

**Comment by JimChiazzese1** [comment]
Many thanks for your work on this @BirenRathod 
I hadn't realised until now (neither had the countries using the app) that we have the same issue for Germany and Brazil (the other countries live on the app), if you're able to duplicate the pages for those countries as well that would be great. 
I met with Claire this morning and we were discussing the FITCount.ceh.ac.uk pages - at this stage I don't think we need the country specific drop down showing for Croatia and Chile as we don't yet have the website translation, so there's a debate if its more confusing to have a country drop down and not change the language or just keep the english pages and add a note to the main page that country specific translations are coming soon. We intend to work on that once we have the remaining countries live. Thanks Jim

For Brazil links should be:
https://fitcount.ceh.ac.uk/br/terms
https://fitcount.ceh.ac.uk/br/privacy-notice

For Germany links should be:
https://fitcount.ceh.ac.uk/de/terms
https://fitcount.ceh.ac.uk/de/privacy-notice

**Comment by BirenRathod** [comment]
@JimChiazzese1 I have added both 'German' and 'Brazil'. For Brazil, Drupal uses pt-br language code, so the page should be fitcount.ceh.ac.uk/pt-br/term & /pt-br/privacy-notice.

Is it possible to change that in the app?

**Comment by JimChiazzese1** [comment]
Thanks @BirenRathod - I think @kazlauskis would have to comment on this. To my knowledge all the other countries follow the two letter code so not sure why Brazil would differ, so I'm afraid I can't say if it can change in the app.

**Comment by BirenRathod** [comment]
@JimChiazzese1 not sure why has he used that code but 'br' is reserved for 'breton'. We might not use that but for Drupal language perspective, it should not have to use another country language.

**Comment by kazlauskis** [comment]
>  For Brazil, Drupal uses pt-br language code, so the page should be fitcount.ceh.ac.uk/pt-br/term & /pt-br/privacy-notice.

Can we make Brazil's website code consistent with other countries and use the `BR` instead?

**Comment by BirenRathod** [comment]
@kazlauskis where is this link -> https://fitcount.ceh.ac.uk/pt/privacy-notice ?

**Comment by BirenRathod** [comment]
@kazlauskis it is consistent, I haven't created. it has been added by language module which is pt-br.

**Comment by JimChiazzese1** [comment]
I'm interested to know where pt comes from? Is that reference to 'portugese' as that's the language of the Brazil app? We are of course currently working with Portugal as well for their version of the app - which will also be in Portuguese, but will defer to allow for regoinal variations. Apologies if this is irrelevant, just curious.

**Comment by JimChiazzese1** [comment]
Thanks @kazlauskis - Please let me know if there's anything I need to do on this, otherwise I assume it's just a case of you and @BirenRathod being in agreement? Thanks
