### ISSUE TITLE
FITCount Website add new pages for Chile Terms/Privacy

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#167]

**Comment by JimChiazzese1** [comment]
Hi @BirenRathod - Please can we create the pages below for the Chile FITCount terms/privacy.
As with all the others, these are duplications of the current English documents until we have the new final versions translated. 
Thanks

https://fitcount.ceh.ac.uk/es-CL/terms
https://fitcount.ceh.ac.uk/es-CL/privacy-notice

**Comment by kitenetter** [comment]
Not yet translated but the pages are available. Closing.
