### ISSUE TITLE
FITCount Portugal spreadsheet content to Transifex

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#168]
Hi @kazlauskis Portugal's content is now all added to the spreadsheet. Please can this up loaded up into Transifex.
I'm away next week so please can you let @CCarvell know when it's available for translation and she can let the portugal team know.
Currently the column is just PT, not sure if that will need to change, but can you provide instruction on how best portugal can review content in transifex with the 'occurence_' search filter, so they can quickly find all their new content for translation. Thanks Jim

**Comment by kazlauskis** [comment]
@JimChiazzese1 @CCarvell I've pushed the new Portuguese texts to Transifex now. New translators should read [this text](https://www.notion.so/flumens/Translations-3e7f4a49dd2244139aa143c5ee97444d), as for filtering just the new Portugal's content they can use [this link](https://app.transifex.com/ceh/fit-count-app/translate/#pt_PT/app/459784838?q=occurrence%3APT+translated%3Ano) - the filter options are embedded in this link. [Here](https://www.notion.so/flumens/Filtering-translations-6275210fbcb94ab5a53413a1a31cd833) is a bit more info about the country filtering.

**Comment by JimChiazzese1** [comment]
Excellent. Many thanks @kazlauskis - I've now shared this with the Portugal team. Jim
