### ISSUE TITLE
Survey - Location page  

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#17]
We need to ensure that a resolution of at least the 1 km square level is located for each count – is it possible to enforce a minimum level of zoom in to the map? 

Please add the following text “ “ behind the “READ MORE” button – but let me know if there is too much text for this box:

“Your location can be anywhere where there are flowers to attract pollinating insects, where you have permission to be, and where it is safe to go. A garden or park, farm or nature reserve are all great locations for FIT Counts. Please zoom in to find the spot that best matches your location. Your count results will be visible to others at the 1 km square level via the UKPoMS website.”

**Comment by kazlauskis** [comment]
What about setting a location outside of the UK? Is the GridRef 1km square restriction for UK users only?

**Comment by kitenetter** [comment]
For UK use we just want to ensure that we don't end up with FIT Counts at very coarse resolutions. I imagine it will be similar for other countries (but they won't be using grid squares in the same way). 

I assume that if using the device GPS the location will be set as precisely as the GPS allows, but if users add the location via the map we want to ensure that they zom in far enough to resolve to 1km square or better for the UK, and a similar zoom setting would be desirable for other countries (but I don't know if this has yet been discussed with project teams from other countries).

**Comment by CCarvell** [comment]
Karolis and Martin - thanks - the desired zoom resolution has not yet been discussed with Cyprus or S America but I would suggest that this is a good place to start. If counts are to be associated with geographical and/or habitat/ environmental features then 1 km or smaller scale would be needed (ie. ideally a 6-fig UK grid ref or equivalent).

**Comment by kazlauskis** [comment]
Thanks, we will restrict the location selection to a certain zoom level then.
