### ISSUE TITLE
FIT Count website - survey filter not needed

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#173]
At the moment, the download pages on the FIT Count website (e.g. https://fitcount.ceh.ac.uk/regional-results) allow the user to choose between the app survey, or the UK PoMS survey, or the UK 1 km square survey. I don't think we need to provide any option other than the app survey.

@CCarvell please can you confirm that anyone accessing data via the FIT Count website only needs to see data that has come from the app. I think the only people who need to use this route will be app users and regional coordinators.

**Comment by DavidRoy** [comment]
Agreed.  All other countries only collect data through the app afaik

**Comment by kitenetter** [comment]
@andrewvanbreda not urgent, but we would like to restrict the reports on the FIT Count website so that they only show samples from the FIT Count app (survey_id = 641). Therefore, the functionality for filtering by survey is not needed.

**Comment by kitenetter** [comment]
@andrewvanbreda has fixed this - closing.
