### ISSUE TITLE
FITCount Brazil - All insect types not showing

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#176]
[download.csv](https://github.com/NERC-CEH/fit-count-app/files/12312285/download.csv)
Brazil report that Fitcount data download does not contain all insect types used by Brazil version of app.
As per attached, insect types showing are: 
Beetles | Bumblebees | Butterflies moths | Honeybees | Hoverflies | Other flies | Other insects | Small insects | Solitary bees | Wasps

Which matches the UK list of insect types.

Brazil insect types used by the app are below (please let me know if you require the name id as used by the app/developer)

Beetles | 418860
Butterflies and moths | 418859
Honeybees | 419001
Other Insects | 418861
Small insects (<3mm) | 419076
Solitary Bees | 418855
Wasps | 418856
Bats | 538661
Hummingbirds | 538662
Orchid bees | 538656
Stingless bees | 538657
Bumblebees sensu lato | 538658
Flies | 538659
Don't know | 538660

The spreadsheet attached was supplied by the Brazil country coordinator, I have been into FITCount.ceh.ac.uk and masqueraded as the Brazil country coordinator and was able to download the same content.
It does not appear that any counts have been submitted in 2023, data is for 2022 only, however I will verify if they know this to be the case.

Thanks

jim

**Comment by andrewvanbreda** [comment]
Hi @JimChiazzese1
I have not looked in detail yet, but there do appear to be samples entered for 2023 looking directly in the Warehouse interface.

**Comment by andrewvanbreda** [comment]
Hi @JimChiazzese1 @DavidRoy @kazlauskis @kitenetter
Further to the email earlier, I see the problem.
Those insect types and currently downloaded in fixed SQL columns in a Regional Coordinator report, these do not take into account new additions to the warehouse, the columns are hard coded.
 I have to change the report.
I can fix this, although there is a slight difficulty as all Regional Coordinators will see all columns (although the data in the column would be empty) unless we change the way this works.

I think best thing is if I change the report and we live with that problem for the immediate term, then revisit this.

I think Brazil probably hasn't got any samples for 2023, although not checked that in detail, but I think that is likely issue.
If it is a problem, it would be a different problem.

**Comment by andrewvanbreda** [comment]
@JimChiazzese1 
It looks like there are 22 rows in the "Insect groups (PoMS)" species list (list 221).
However in the download report there are only 10 columns.
So to fix this issue properly we need 12 new columns in the download file.
Is that ok?

I think this problem could potentially affect other regional coordinators too, at least in theory.

**Comment by JimChiazzese1** [comment]
Thanks @andrewvanbreda That sounds about right. It could get a little confusing as some countries have butterflies and moths as one category, where others have them seperated. However, each country should know what categories apply to them and should easily be able to filter csv as necessary, so I don't think it will be issue introducing the extra columns. I can also ensure that country coordinators are a bit more thorough when checking, as this is something that they should have picked up on initial testing.

**Comment by andrewvanbreda** [comment]
Hi @JimChiazzese1 
Fix is live.
I have tested on a sample that used a different abundance number for each of the 22 insect categories and it all looked right in the report.
Close if you are happy, or comment further.

**Comment by JimChiazzese1** [comment]
Thanks @andrewvanbreda This looks good to me. I've asked Brazil to download report and confirm it meets with their expecations, but just seeing the number of counts for stingless bees (Brazil only category) indicates all is good. Many thanks
