### ISSUE TITLE
FITCount - Sweden spreadsheet content to Transifex

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#177]
- [x] Sweden have now updated all their content and the spreadsheet has been updated, please can the updated content be transferred to Transifex.
 - [x] Noticed one strange issue on the spreadsheet, when I filter to just show Sweden's TRUE entries on the insect guide tab, it also shows all the entries for portugal, which I assume is related to the sheet formating somehow? Please let me know if there's anything I can do to support that.

- [x] New flower images have been uploaded to Flumens - Flowers - All Documents.
There are no new insect images

- [x] There are two additional photographers to add to the credits (otherwise same as UK app) - Stefan Andersson and Jan Thomas Johansson

![image](https://github.com/NERC-CEH/fit-count-app/assets/84846811/cb7e3b4d-43a9-40e2-99e9-05603fc8acde)

**Comment by kazlauskis** [comment]
I think, we're missing `socialwasps_1.jpg`.

**Comment by kazlauskis** [comment]
Regarding the Swedish data filtering, the sheet is formatted as a fixed table. If we add any more rows in the MIDDLE of the table, then Excel is smart enough to expand the table to accommodate these. But any new rows added BELOW the table need to be added to the table by us. You can do that by increasing the table area by dragging this little table corner handle:

<img width="1005" alt="Screenshot 2023-09-02 at 16 56 59" src="https://github.com/NERC-CEH/fit-count-app/assets/7383162/bd818d83-744c-4c02-9e3c-bb2d7a19b2b8">

**Comment by JimChiazzese1** [comment]
> I think, we're missing `socialwasps_1.jpg`.

![socialwasps_1](https://github.com/NERC-CEH/fit-count-app/assets/84846811/d589b473-4c0e-41e6-a01f-8b171004a6cf)

Please find attached. For some reason the Flumens insect folder won't let me upload this. Thanks. Jim

**Comment by JimChiazzese1** [comment]
Hi Karolis, Sorry if it's just me, but I get a blank when viewing the social wasps, but then this ticket is just for moving content to transifex. Let me know if we need another ticket to import all to the online demo. Thanks Jim

**Comment by kazlauskis** [comment]
OK, fixed it now. The issue was that in the `insects` sheet we used "socialWasps" and in the `insect-guide-photos` we had "socialwasps". The species IDs must match across the sheets and also files for the app to find the species descriptions and photos.
