### ISSUE TITLE
FITCount - Google Play target API Level requirements

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#178]
Update of FITCount to target the latest Android version by End August, as per Google Play Console instructions

**Comment by JimChiazzese1** [comment]
![IN_APP_EXPERIENCE-9683](https://github.com/NERC-CEH/fit-count-app/assets/84846811/7a7803f7-b321-4662-9027-fe83490bd2da)

Have forward on the lastest from Google, suggesting that it's still not compliant...but as I was away and that email may have been before you closing this, it might be that it's already sorted. In which case, please do close again! Thanks Jim

**Comment by kazlauskis** [comment]
@JimChiazzese1 thanks, I am also receiving these emails. For some reason, they made a mistake and sent us this warning again. Not sure what has happened, but it seems the app submission was accepted after all and the latest version 1.5.2 (207) is live.
