### ISSUE TITLE
FITCount app - Argentina to live

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#179]
Argentina have test the online version and are ready to move live. 
There is not a rush for this, if it's easier we can wait and move Sweden live at the same time if that helps.
Thanks

**Comment by kazlauskis** [comment]
It would be easier to release both SE and AR simultaneously to the public.

**Comment by JimChiazzese1** [comment]
Thanks. Will have the warehouse updated accordingly and let you know when Sweden are happy to go live.
