### ISSUE TITLE
"Refresh token is invalid" message in FIT Count website logs

### ISSUE THREAD

**Issue by andrewvanbreda** [NERC-CEH/fit-count-app#182]
@BirenRathod @kazlauskis 
I am noticing this error in the FIT Count webisite logs (appearing multiple times) I hope this doesn't mean the app is failing from the Drupal 10 website upgrade?

League\OAuth2\Server\Exception\OAuthServerException: The refresh token is invalid. in League\OAuth2\Server\Exception\OAuthServerException::invalidRefreshToken() (line 229 of /code/vendor/league/oauth2-server/src/Exception/OAuthServerException.php).

**Comment by BirenRathod** [comment]
@andrewvanbreda I noticed too but need confirmation from @kazlauskis if the app is working or not. This could be for any apps not just fitcount as the same module is applied to all websites.

**Comment by kazlauskis** [comment]
This means that existing user sessions are invalid and users will have to relogin. Not the end of the world, but unlike websites, typically mobile app users don't expect to relogin to the apps. This has happened during another Drupal version upgrade in the past. I am not an expert in this, so I don't know how to prevent it, but maybe when upgrading Drupal, there is something you can do to prevent this.

**Comment by BirenRathod** [comment]
@kazlauskis Just for info to let you know that there were things happened here. 1. simple_oauth module upgraded 2. Drupal upgraded. so is this the simple cause of the Drupal upgrade or the consequences of both? Also, another upgrade for simple_oauth is pending. I will investigate it.

**Comment by kazlauskis** [comment]
The last time it happened, I think we have only upgraded the Drupal. It was moved to a new Pantheon deployment then. My guess it could have lost some local temp files or something that the module requires to validate refresh tokens. I am not sure what happened during this upgrade.

**Comment by kazlauskis** [comment]
OK, I have checked this now more closely and can confirm that when websites are upgraded with new deployments instead of in-place, users have to relogin. @BirenRathod, can we make these Drupal version jumps without creating new parallel Pantheon entries? 

On Pantheon, I can see we have brc-ebms and brc-ebms-10, brc-irecord and brc-irecord-10 etc, users have to relogin on all the apps linked to those websites.

**Comment by BirenRathod** [comment]
@kazlauskis can you give more details about the Drupal version jump bit? I don't understand. The old websites are no longer in use technically as there is no URL linked to them. for e.g. brc-ebms & brc-irecord are no longer in use.

**Comment by kazlauskis** [comment]
For some reason, if a website is moved to a new Pantheon deployment (site), the simple_oauth module doesn't recognise the current refresh_tokens (user sessions). I am not sure how the migrations are done, but could there be some temporary files that aren't moved or maybe some DB values changed when doing such upgrades? 

Can Drupal 9 to Drupal 10 upgrade be done on Pantheon within an existing site? i.e. without creating a new Pantheon deployment.

**Comment by BirenRathod** [comment]
@kazlauskis I created new upstream for Drupal 10 but it migrated within Pantheon, so I can all file & folders structure same.
