### ISSUE TITLE
Survey - Target flower

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#19]
Species (in blue) – replace with “Target flower chosen”

After “Other” where it says “Manual entry” – replace this with “Other flower name” instead – on clicking this can we add text “Please type in the name of the target flower you have chosen then go back to the target flower page”

Note that Martin was unable to see the other flower option in the demo version he was viewing, is there a glitch here?

Please add the following text behind the i info tab at the top:

“ Where possible please choose a patch of flowers from one of the target flower groups in the list. If none of these is available at your location you can choose another flower that is attracting insects and select “Other”, then type in the name. Your target flower can be growing in a patch all of the same flower, or among different flower species. For each FIT Count, please upload one or two photos of your target flower. This allows us to double-check the flower species used for the counts.”

**Comment by kitenetter** [comment]
On this page, where it says "Photos", change to:
Photo of your target flower

**Comment by kazlauskis** [comment]
Thanks, we'll change this.
