### ISSUE TITLE
Question re average numbers in the app

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#195]
@kazlauskis at the end of a FIT Count the app shows the average number of insects counted during the current month. I'm fairly sure that this is based on some static data that we provided to you, and it is not calculated from the 'live' data. Please can you confirm?

**Comment by kazlauskis** [comment]
@kitenetter yes, that's right. The app has a built-in static dataset for the UK stats.

**Comment by kitenetter** [comment]
Thanks.
