### ISSUE TITLE
Privacy policy & T&Cs

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#2]
Take from Funder project Contracts? Or UKCEH GDPR???

**Comment by kitenetter** [comment]
Since the user accounts are being stored by UKCEH I think we will have to have something that is similar to the iRecord Privacy Notice, although other examples could be taken from the EBMS app or the European Ladybirds app.

There is no dedicated website for this app (other than the 'headless' website that we are using for the user accounts), so I think we will have to have the privacy notice stored within the app itself, rather than as a weblink as happens on several of the other apps. This privacy notice will have to apply to user accounts for all countries.

For the Terms of use we might also have to come up with one set of terms for all countries, but I am less clear about this. We could link things so that if the user chooses UK as their country, the Terms of use become a link to the UK PoMS website. But at least initially not all other countries will have dedicated websites, so we would still need a generic terms of use for all app users, and that is probably the simplest thing to do.

Will provide draft text.

**Comment by kitenetter** [comment]
Text now drafted and being reviewed via Teams with @DavidRoy and Claire

**Comment by CCarvell** [comment]
Martin - can you confirm where this 'text now drafted' is? Will we still have to have separate links to Privacy Policy AND T&Cs? The app registration page suggests this:
"_By clicking Sign Up, you agree to our Privacy Policy and Terms and Conditions_"

As the FIT Count app accounts website is:
fitcount.ceh.ac.uk
then we should probably link to the UKCEH privacy notice: https://www.ceh.ac.uk/privacy-notice
This states "By visiting www.UKCEH.ac.uk **and affiliated websites** you are accepting and consenting to the practices described in this policy."

**Comment by DavidRoy** [comment]
PoMs is a partnership project so the privacy notice should be freestanding, although can link to the UKCEH policy

**Comment by kitenetter** [comment]
@CCarvell I added you to a Teams channel, which is where the draft Privacy Notice currently sits:
https://teams.microsoft.com/_#/school/files/PoMS%20and%20FIT%20Count%20development?threadId=19%3A397dc2f55a154936974a15c25e0b1901%40thread.skype&ctx=channel&context=PoMS%2520and%2520FIT%2520Count%2520development&rootfolder=%252Fsites%252FBRC-PoMSandFITCountdevelopment%252FShared%2520Documents%252FPoMS%2520and%2520FIT%2520Count%2520development

Quentin has seen it and I now need to incorporate his comments. There is a link the UKCEH Privacy Notice.

We have to have a privacy notice. Terms of use are desirable but not essential - however, I am intending to compile them.

**Comment by kitenetter** [comment]
The text for the FIT Count app Privacy Notice needs to be added to the http://fitcount.ceh.ac.uk website, and then linked from the app. The text is here:

[FIT Count Privacy Notice v1.docx](https://github.com/NERC-CEH/fit-count-app/files/6101867/FIT.Count.Privacy.Notice.v1.docx)

Matters arising:
1. I have given the location of this notice as `http://fitcount.ceh.ac.uk/privacy-notice` - can Biren confirm this is correct, and to set up that page to store the text (I don't seem to be able to tag Biren in this issue)
2. We also need a second page to be set up to store the text for a Welsh translation of the Privacy Notice
3. The text then needs to be translated - I think we are going to do this via transifex but can @DavidRoy confirm please
4. @kazlauskis to add a links to the correct URL, based on user language choice, from within the app

Question:
Where we have an English version and a Welsh version of the same page, will they have completely different URLs, or will it be one URL with a different suffix for each language?

**Comment by kazlauskis** [comment]
I can link the app to whatever language page, is Biren doing the site?

**Comment by DavidRoy** [comment]
I'll liaise with Biren to get http://fitcount.ceh.ac.uk/ setup

**Comment by kitenetter** [comment]
The text for the FIT Count Terms of Use needs to be added to the http://fitcount.ceh.ac.uk website, and then linked from the app. The text is here:

[FIT Count Terms of Use v1.docx](https://github.com/NERC-CEH/fit-count-app/files/6102433/FIT.Count.Terms.of.Use.v1.docx)

Matters arising:
1. I have given the location of this notice as http://fitcount.ceh.ac.uk/terms - Biren to set up that page to store the text
2. We also need a second page to be set up to store the text for a Welsh translation of the Terms of Use
3. The text then needs to be translated
4. @kazlauskis to add a links to the correct URL, based on user language choice, from within the app

**Comment by DavidRoy** [comment]
@BirenRathod can you create pages for ../terms and ../privacy-notice on https://test-ceh-fitcount.pantheonsite.io/

**Comment by BirenRathod** [comment]
@DavidRoy & @kitenetter Those links have been created and placed at the footer.

@kazlauskis Let me know when you ready to go for live, so I can point website to fitcount.ceh.ac.uk URL

**Comment by DavidRoy** [comment]
Thanks @BirenRathod 
We can go live with this site as it's easier to test everything

**Comment by BirenRathod** [comment]
Thanks @DavidRoy. Ok, I will let you soon about it.

**Comment by BirenRathod** [comment]
@DavidRoy  Translation pages have added now. However the text in those pages still in English, so may be require to translate.

**Comment by BirenRathod** [comment]
@kitenetter I made you Admin, so you can implement that now.

**Comment by BirenRathod** [comment]
@DavidRoy , @kitenetter , @kazlauskis & @CCarvell 
Just to let you know that fitcount.ceh.ac.uk is live now.

**Comment by kitenetter** [comment]
I think we can close this.
