### ISSUE TITLE
Survey - Number and type of flowers in patch

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#21]
Please BRING THIS PAGE BEFORE THE TARGET FLOWER COVER PAGE
Edit top title text to say “What are the type and number of flowers in your patch?

Put the number slider at the bottom, bring the 4 types up the screen.

Type – can this be pre-populated IF the selected flower is from the target flower list to ensure consistency? See list below.

Flower number – can we leave the slider with a max up to 200 BUT cap the free text entry at 5000? (about 5% of counts so far are over 200)

Please add the following text behind the i info tab at the top: [is this too much? note to edit IF flower TYPE cannot be pre-populated by default]
"The number of flowers in a patch can strongly relate to the number of insect visitors recorded, so it is important to provide this information! Only count flowers that are reasonably fresh and likely to attract insects – ‘dead-head’ flowers and seedheads should not be counted. Flowers need to be counted in different ways depending on their structure. If you have chosen a target flower from our list, the flower type is shown by default. If you have chosen “Other” target flower, please count:
individual flowers - each flower counts as one unit
flower heads (where there are lots of tiny flowers within a larger flower head, e.g. dandelion or daisy) – each flower head counts as one unit
umbels (for flowers that have small flowers grouped into ‘umbels’, like inside-out umbrellas, e.g. hogweed) – each umbel counts as one unit
spikes (where a number of small flowers are arranged along a stem, e.g. lavender) – each spike counts as one unit "

**Main flowering time | Target flower name | Flower   type**

Apr   to Sep | Buttercup   – Ranunculus species | individual   flowers
Apr   to Sep | Dandelion   - Taraxacum officinale | flower   head
Apr   to Jun | Hawthorn   – Crataegus | individual   flowers
Apr   to Sep | White   Dead-nettle - Lamium album | flower   spike
May   or Jun to Sep | Bramble   (Blackberry) - Rubus fruticosus | individual   flowers
Jun   to Aug | Lavender   (English) - Lavandula angustifolia | flower   spike
Jun   to Sep | Hogweed   - Heracleum sphondylium | umbel
Jun   to Sep | Knapweed   (Common or Greater) - Centarea nigra   or scabiosa | flower   head
Jun   to Sep | Ragwort   - Senecio jacobaea and relatives | flower   head
Jun   to Sep | White   Clover - Trifolium repens | flower   head
Jul   to Sep | Buddleja | flower   spike
Jul   to Sep | Heather   - Calluna vulgaris or Erica species | flower   spike
Jul   to Sep | Thistle   - Cirsium or Carduus | flower   head
Sep | Ivy   - Hedera helix | flower   head

**Comment by kazlauskis** [comment]
> Flower number – can we leave the slider with a max up to 200 BUT cap the free text entry at 5000? (about 5% of counts so far are over 200)

The slider component is tightly coupled to the manual entry and +/- buttons at the moment and it works logarithmically for large numbers - allowing for precise sliding initially but then makes bigger increases the more you slide. Most of the times the user wouldn't be counting over 1000 flowers manually but estimating.  

We can customise the component if this isn't good enough but I wonder if there is an easier way here by using a max number that is somewhere in the middle? Maybe up to 500 or 1000 instead?

**Comment by kitenetter** [comment]
The problem is that in previous years some FIT Counts have reported up to 5,000 individual flowers. In some cases this is likely to be a result of users misinterpreting what they are being asked to count, but there do seem to be genuine counts up to around 2,500 at least.

If we cap below that amount, what will users do if they do encounter a situation that genuinely has a larger number? I guess they would either abandon the survey or provide an erroneously low count, neither of which are good options.

A cap of 3,000 would likely be okay for all but the most exceptional of circumstances.

**Comment by kazlauskis** [comment]
I see, I can make it 5000 if you are expecting numbers that hight.

**Comment by kitenetter** [comment]
I'm inclined to go for 3000 I think.
