### ISSUE TITLE
Survey - add intro page before count

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#24]
The intro alert will look like this:

<img width="367" alt="Screenshot 2021-03-11 at 16 07 32" src="https://user-images.githubusercontent.com/7383162/110817194-f5237380-8283-11eb-9021-4de8484d67af.png">

**Comment by kazlauskis** [comment]
Do you want to show this intro page on every survey? I don't think we need any background images for the count page, on small screen devices it would then look too busy. We could change the colouring though.

**Comment by CCarvell** [comment]
Yes please, show this holding page on every count, but those who have done it before can hit "Start count" straight away.
No problems with changing colour, but if you think there is a good colour that breaks up the survey a bit, we could try it.

**Comment by CCarvell** [comment]
We think it's best to have control on the count page itself, but the key thing for the count page is to be able to pause if needed.
This is why I suggested the text "When you are ready, select ‘Start count’ – you will have a chance to start and pause the timer on the next page"
I can see this being helpful to people using the app in groups, where they are training or using it for the first time. So you get to look at the position of the different insect icons on the count page and you know where you are, before the timer starts.
is that OK?
I have to go and get a car tyre replaced now! C

**Comment by kazlauskis** [comment]
OK, we can keep the countdown deactivated when the user opens up the count page then.

**Comment by kitenetter** [comment]
We discussed changing the text for this pop-up page. Will this work or is it still too long:

You are now ready to start your FIT Count!

- Count every insect that lands on the target flowers (ignore other flowers, and do your best to count each individual insect once only!).
- Tap on the insect images to increase your count (use the minus buttons if you need to decrease the count).
- If you are not sure of the insect group, add it to the "Other insects" category.

When you are ready, select "Start count" and the timer will start.

**Comment by kazlauskis** [comment]
Thanks, if possible, I would shorten this still. In the Welsh language, some English texts will expand and if we want to present all the bullet points without scrolling down then I would at least remove the last sentence which I don't think is necessary. 

<img width="369" alt="Screenshot 2021-03-11 at 19 31 38" src="https://user-images.githubusercontent.com/7383162/110843613-683ae300-82a0-11eb-93f3-ae5a526b703c.png">

**Comment by kitenetter** [comment]
Can we go with:

The timer will now start!

    Count every insect that lands on the target flowers (count each individual once).
    Tap the insect images to increase your count (minus buttons will decrease the count).
    If you don't know which insect group, add to the "Other insects" category.

**Comment by CCarvell** [comment]
I'm happy with this shortened version from @kitenetter and good to have the tap and minus buttons explained.
