### ISSUE TITLE
Remove info button and add count minus button.

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#25]
Remove info button and add count minus button.
<img width="325" alt="Screenshot 2021-03-11 at 16 11 21" src="https://user-images.githubusercontent.com/7383162/110818276-06b94b00-8285-11eb-9949-2d76b8bf91bf.png">

**Comment by kazlauskis** [comment]
In one of our early meetings, we have decided that the `info` icon would act as a button that would open the insect profile with options to change the count number manually at the top of it. Is that no longer the case?

**Comment by kazlauskis** [comment]
Where would you like to have the number change option added then? Instead of an icon, we could use a long-tap to open up an extra screen with further options.

If we want to show 6 species per page then there wouldn't be enough space for a note above the species tiles on small-screen devices.

**Comment by CCarvell** [comment]
Ideally we would have the simplest display possible to allow users to tally the count but also to change their choices if a mistake is made (ie so you can plus or minus) without any complex long tap option. Sorry I'm probably not understanding the options very well, probably best to demo at the meeting if possible.
