### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#28]
Will this new text fit in to replace current?

“The Flower-Insect Timed Count (FIT Count) is a 10-minute survey designed to collect new data on numbers of flower-visiting insects. 
FIT Counts are suitable for all, in urban or rural locations, and can be done at any time between the beginning of April and end of September.
Wild pollinators may have declined in the UK by more than 30% since 1980, but we need much more data to be able to track changes in abundance. You can help by doing a FIT Count, maybe even repeating it over the season. You don’t need to identify the insects to species level, only to within broad groups e.g. bumblebees, hoverflies, butterflies & moths, wasps.
The FIT Count is part of the UK Pollinator Monitoring Scheme (PoMS), within the UK Pollinator Monitoring and Research Partnership which comprises the UK Centre for Ecology & Hydrology (UKCEH), Bumblebee Conservation Trust, Butterfly Conservation, British Trust for Ornithology, Hymettus, Reading University, University of Leeds and Natural History Museum. PoMS is jointly funded by Defra, the Welsh and Scottish Governments, Daera, JNCC and project partners.

For further information about PoMS go to: NEW WEBSITE LINK “

Partner logos: re-order with UKCEH first left, then order as in the list above.
Funder logo to add Daera – to supply

**Comment by Vilius-Stankaitis** [comment]
Can I use this logo for Daera?
![DAERA.png](https://zube.io/files/nerc-ceh/9d3fe102d392b7ed83a8a0110ba553de-daera.png)

**Comment by CCarvell** [comment]
@Vilius-Stankaitist this is the Deara logo that I have been asked to use - not sure if it matches your version but was supplied by Daera for us. I also have an EPS version that won't attach here if that is preferred.
![A4 DAERA Logo process with correct spacing](https://user-images.githubusercontent.com/44494345/110489459-5530e300-80e7-11eb-987f-b65f00bdc9f2.jpg)

**Comment by kitenetter** [comment]
@CCarvell Biren has said that it is best to use ukpoms.org.uk, but www.ukpoms.org.uk will also work.

**Comment by BirenRathod** [comment]
@kitenetter yes, that is correct

**Comment by kazlauskis** [comment]
OK, we'll use the `ukpoms.org.uk` then.
