### ISSUE TITLE
Credits page

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#29]
Slight tweak in wording “We are grateful to all the people who helped to create this app:”

Please add:
David Roy (UKCEH)

Question – how do we acknowledge minor contributions from PoMS team members? There are more UKCEH people but the list will become too long!

Under Graphics please add:
FIT Count logo: Heather Harris (UKCEH)

**Comment by CCarvell** [comment]
Are we expecting this Credits page to be edited and translated for Cyprus and S America? I think it willl have to be for flexibility and alternative photo credits etc, but also we should acknowledge the contributions of Francisco et al and other projects to the overall app concept.

I agree with Martin re PoMS team as it is too big - how about generic acknowledgement to the project teams involved:

"Team members of the following projects:
UK Pollinator Monitoring Scheme (UK PoMS)
Safeguarding pollinators and pollination services in a changing world (SURPASS2)
Pollinator Monitoring Scheme – Kýpros (PoMS-Ký)"

Definitely include those photo credits as Martin suggests.

**Comment by DavidRoy** [comment]
I think it's simpler to have a single credits page. I agree on the generic project acknowledgements plus naming individual photographers

**Comment by kazlauskis** [comment]
I agree, let's keep it on a single page for now. Do we need to translate the project names?

**Comment by CCarvell** [comment]
@kazlauskis I do not think these project names need translating to Welsh, if that is what you mean
