### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#3]
Create a Drupal8 website for user accounts.

**Comment by kazlauskis** [comment]
@BirenRathod we are following the same website set up procedure like for the other projects, is that right? When the dev site is ready then please give me admin access to it and let me know when I can install any of the extra modules. Cheers

**Comment by BirenRathod** [comment]
@kazlauskis Everything is same at present.

**Comment by BirenRathod** [comment]
@kazlauskis Dev site has created now, please register on it. I will then make you admin.
Here is the URL -> https://dev-ceh-fitcount.pantheonsite.io/

**Comment by kazlauskis** [comment]
That's done now. Will you give me access on Pantheon as well?

**Comment by BirenRathod** [comment]
@kazlauskis I have activated your account and made you admin now.

**Comment by kazlauskis** [comment]
Thanks!
