### ISSUE TITLE
Register page

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#30]
How did you hear about FIT Counts?

Claire to provide final list for selection

Identification experience - there are only 2 options here - can we have all 4 options on the current FIT Count form?

**Comment by DavidRoy** [comment]
You could remove 'I am' from each option to reduce text?

Ideally this text would all appear on a single option box?

**Comment by kazlauskis** [comment]
Thanks, we'll remove the 'I am'. What's the single option box you mean?

**Comment by DavidRoy** [comment]
Thanks.  I mean that the text all appears without the need to scroll.  So users don't miss the 4 choices
