### ISSUE TITLE
Insect guide photos and text

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#31]
@kazlauskis the zip file below contains photos for each insect group, and text annotations for all groups are in one spreadsheet.

Let me know if anything is unclear or needs to be presented in a different way.

[FIT Count app insect guide.zip](https://github.com/NERC-CEH/fit-count-app/files/6111894/FIT.Count.app.insect.guide.zip)

**Comment by kazlauskis** [comment]
Thanks!
