### ISSUE TITLE
App screen shots for Funder update

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#32]
@kazlauskis @Vilius-Stankaitis is there any chance you could send me **4-5 screen shots from the current version of the app demo** please? The Funders are asking for an update - and our Defra project officer has her last day TODAY so I would like to provide this today if possible....sorry!
The opening screen with FIT Count logo and Start Survey, plus a couple of survey screens (incl insect count page) and registration page would be perfect. 
Are you able to email these as smallish file size to ccar@ceh.ac.uk?

**Comment by kitenetter** [comment]
I can sort this out Claire, based on screenshots from https://fit.app.flumens.io/demo.html (I assume that is all you need?).

**Comment by kitenetter** [comment]
@CCarvell here are some screenshots.

[App screenshots 2021_03_10.zip](https://github.com/NERC-CEH/fit-count-app/files/6114939/App.screenshots.2021_03_10.zip)

**Comment by CCarvell** [comment]
perfect thank you Martin! I thought Flumens might have a different/ quick way of exporting app screen images but this is ideal.

**Comment by kitenetter** [comment]
Closing.
