### ISSUE TITLE
Show thank you message after the survey

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#33]
This will look like this:

<img width="370" alt="Screenshot 2021-03-11 at 16 05 00" src="https://user-images.githubusercontent.com/7383162/110816906-ae357e00-8283-11eb-8330-a04b364acd2b.png">

Email dialogue fo

Thanks all, and Martin did a great job of quickly generating the averages.

I think the intention was to focus on developing the feedback and visualisation tools within the UK PoMS website and bring these across to the app as and when appropriate. However, if there is a page devoted on the app to saying thank you and encouraging a user to return for another count, let’s make the most of it if we can?

1.	If Option 2 is possible without any fancy graphics then I agree with Martin, the average per month is much more meaningful. But it would need to update each time we move to a new month. SEE OPTION 1 AVERAGES BELOW
![RSPB nationwide so far](https://user-images.githubusercontent.com/44494345/110614631-71d22700-818a-11eb-97c3-f0ff2b15b6dd.jpg)
![RSPB your birds](https://user-images.githubusercontent.com/44494345/110614676-7c8cbc00-818a-11eb-9ed1-060370d3c78e.png)

We could also hold back on additional detail until we work out exactly which datasets the website visualisation tools will be taking from – public and/or 1km square.
Martin provided averages for public and 1km FIT Counts in 2019 and 2020 but our previous donut graphics were just based on the public counts (more biased to gardens), and our analysis still treats the pubic and 1km FIT Count datasets separately.

2.	Fine to ignore as David suggests until we get towards September

3.	Non-UK countries will have to start with a simple thank you page and possible total number counted but no comparison data.

Could we see a mock-up of this on Thursday perhaps?
Claire

Option 1 was to show the user's count in comparison with the average for all counts.

That average is 11.14 insects per count (based on all FIT Counts from 2019-20).

I think it would be fine to keep that simple and just say the average is 11 insects per count.

Martin

________________________________________
From: Roy, David B. <dbr@ceh.ac.uk>
Sent: 09 March 2021 12:35
To: Harvey, Martin C. <marharv@ceh.ac.uk>; Karolis Kazlauskis <karolis@flumens.io>
Cc: Carvell, Claire <ccar@ceh.ac.uk>
Subject: RE: FIT Count app finish and feedback options 
 
For the first version, the priority is giving some simple feedback. I suggest we aim for option 1 only.  
Ignore the complication of counts outside of the April-September period as that is some way off.  Similarly, don’t worry about the non-UK data.
 
Thanks
David
 
From: Harvey, Martin C. <marharv@ceh.ac.uk> 
Sent: 09 March 2021 12:10
To: Karolis Kazlauskis <karolis@flumens.io>
Cc: Carvell, Claire <ccar@ceh.ac.uk>; Roy, David B. <dbr@ceh.ac.uk>
Subject: Re: FIT Count app finish and feedback options
 
1 Ideally needs input from someone who can design graphics, but I don't think we have time for that. The message we want to get across is:
 
Thanks for completing your FIT Count - all results help us to monitor insect populations.
 
You counted X insects altogether - the average total for [month] is Y
 
This is how your insect group counts compare:

2 Surveys in the UK can only be done from April to September. If people try to do a survey outside those months we should warn them, and either disallow data entry altogether, or warn that their data cannot be included in the FIT Count analysis.
 
3 I'm not aware of this having been discussed yet for non-UK countries, nor am I aware of similar comparison data being available to populate the averages. So probably all we can do for now is to use similar wording to thank people for their count and summarising their totals for the species gropus involved, but with the comparison averages.
 
Martin
 
 
 
________________________________________
From: Karolis Kazlauskis <karolis@flumens.io>
Sent: 09 March 2021 11:45
To: Harvey, Martin C. <marharv@ceh.ac.uk>
Cc: Carvell, Claire <ccar@ceh.ac.uk>; Roy, David B. <dbr@ceh.ac.uk>
Subject: Re: FIT Count app finish and feedback options 
 
Thanks, that looks good. A few immediate questions: 
 
1.	How would you like me to present the feedback?
2.	What about surveys done outside these months?
3.	How should it appear for surveys done in countries where the species lists differ? 
 
Cheers
 
Karolis Kazlauskis
Software Consultant
+44 (0) 123 588 6422
Flumens | 10A St Mary’s st, Wallingford, UK

On 9 Mar 2021, at 11:40, Harvey, Martin C. <marharv@ceh.ac.uk> wrote:
 
Karolis,
 
Here is data for the average number of insects counted per month. One worksheet shows the total number of insects per count, the other shows the total for each insect group per count.
 
Is this sufficient for you to generate the option 2 feedback?
 
Claire: this is based on all public and 1km FIT Counts in 2019 and 2020 (partly because those two years have the most counts, partly because those are the years I have immediately to hand).
 
Martin
 

From: Carvell, Claire <ccar@ceh.ac.uk> 
Sent: 08 March 2021 22:56
To: Harvey, Martin C. <marharv@ceh.ac.uk>; Karolis Kazlauskis <karolis@flumens.io>
Cc: Roy, David B. <dbr@ceh.ac.uk>
Subject: FIT Count app finish and feedback options

Hi Karolis, Martin,

Thanks for this interesting thread – Martin perfectly summarises the brief discussion we had (sorry I had not had time to get it over onto GitHub last week).
I also agree that Option 2 is a great feedback measure (easy to generate and to understand for a new user). 

This kind of feedback is similar to the RSPB Big Garden Birdwatch – see attached – they provide over two screens 
a) Thank you b) Your top 5 birds (half pie chart) c) Nationwide results so far (this year) d) Last years’ results
But we should probably start simpler than this for the app?!

Karolis, as Martin says Andy and Rich have been working up feedback options for the website and I was keen to understand what cross-over these could have with the app and mobile screen interface (though I think Andy is designing the web feedback to show on a smartphone too).

Rich Burkmar has produced these demo figures by insect group for each target flower (not by country yet), based on graphics Martin developed last year:
https://biologicalrecordscentre.github.io/brc-charts/docs/example-1.html 
So for the website at least, we might compare “your count” vs “national average” on this target flower, similar to Martin’s Option 3. To make it work from the start, it would be better to pre-populate with 2020 or 2018-20 national average data (per month or whole year).
Something to discuss in our meetings this week if possible?

Thanks,
Claire

From: Harvey, Martin C. <marharv@ceh.ac.uk> 
Sent: 05 March 2021 18:17
To: Karolis Kazlauskis <karolis@flumens.io>
Cc: Carvell, Claire <ccar@ceh.ac.uk>; Roy, David B. <dbr@ceh.ac.uk>
Subject: Re: app Demo survey Edits added to GitHub

My only concern is whether we should give the user the choice of only uploading when using wifi. The photo of the target flower could use quite a lot of data if not on wifi?

Andy and RIch have been working on similar feedback options for the website but again I don't think we have yet reached a conclusion over exactly what this will consist of. Maybe David can say more, but otherwise I'll need to liaise with Andy/Rich.

Martin

________________________________________
From: Karolis Kazlauskis <karolis@flumens.io>
Sent: 05 March 2021 17:51
To: Harvey, Martin C. <marharv@ceh.ac.uk>
Cc: Carvell, Claire <ccar@ceh.ac.uk>; Roy, David B. <dbr@ceh.ac.uk>
Subject: Re: app Demo survey Edits added to GitHub 
 
Thanks, I like that. When the user taps ’Save my count’ why don’t we upload the survey automatically? The app can detect if the device has a network connection and if it has then it would upload it to the warehouse + show thanks/report, otherwise, it would take the user to the surveys list + show thanks/report. 

I can do either of the feedback options and the user-specific reports sound great. A big part of this comes down to the report as we would need a report that accepts a userID and a countryID and returns the relevant data - can Andy/John do the report for us or does the website already have something similar we could use?

Cheers

Karolis Kazlauskis
Software Consultant
+44 (0) 123 588 6422
Flumens | 10A St Mary’s st, Wallingford, UK

On 5 Mar 2021, at 16:24, Harvey, Martin C. <marharv@ceh.ac.uk> wrote:

Claire and I did discuss this, and Claire has the notes from that discussion, but from memory I think what we said was:

•	Page 10: fill in the wind strength
•	"Save my count" button then appears, giving the user the chance to step back through the survey and edit before they save
•	When they click Save, they are asked:
o	Send your count to the PoMS website now (requires data connection)
o	Save your count on this device and send to website later
•	They are then taken to a new page that says:
o	"Thank you for carrying out a FIT Count! Please make sure you send the count to the PoMS website if you have not already done so."
•	And then ideally we show some feedback to put their count into context.

We haven't yet discussed what this feedback should be. Options that I can think of are:
1.	Show the user's total number of insects in comparison with the average number of insects per FIT Count (across all counts, maybe also taking UK country into account???)
2.	Show the user's total number of insects in comparison with the average number of insects per FIT Counts that have happened in the same month (or week?) (across all years, maybe also taking UK country into account???)
3.	Show the user's total number of insects in comparison with the average number of insects per FIT Counts on the same target flower (across all years, maybe also taking UK country into account???)
4.	Show the user's total number of insects in comparison with the average number of insects per FIT Counts on the same target flower and in the same month (across all years, maybe also taking UK country into account???)

Or we could go a stage further and break things down into insect groups, showing the user's count of each group against one or more of the averages shown above.

Option 1 above would be a bit dull in that the average shown would be very slow to change.

Option 2 is my favourite, in that it will change over time and will encourage users to repeat their counts during the year.

I've suggested filtering by country, but I suspect that is a complication too far?

I don't know whether it is realistic to calculate these averages against the live PoMS dataset (which I assume could only happen if the user had a data connection, and for which we would also need to know exactly how the data is being stored in the new PoMS website within the data warehouse). Or whether we should instead pre-populate the app with some static average counts that could be used without a data connection (if we take that approch I can provide suitable data).

Let me know which, if any, of these options seem most feasible, or whether this needs to be a version 2 feature.

Martin

________________________________________
From: Karolis Kazlauskis <karolis@flumens.io>
Sent: 05 March 2021 15:38
To: Carvell, Claire <ccar@ceh.ac.uk>; Harvey, Martin C. <marharv@ceh.ac.uk>
Cc: Roy, David B. <dbr@ceh.ac.uk>
Subject: Re: app Demo survey Edits added to GitHub 
 
Hi Claire and Martin

Have you had some time to think how you would like the survey to finish? Some ideas: 

1.	Last weather question has a “Finish" button instead of “Next" and that would take to the user surveys list page.
2.	An extra screen with the current survey summary is displayed at the end of the questions, i.e step 11 = summary.
3.	An extra screen at the end to say thank you - if it is a sentence or two this might be better shown as a popup when the user clicks ‘Finish’ instead of a dedicated page.

Cheers

Karolis Kazlauskis

**Comment by kazlauskis** [comment]
Average insect numbers:

[feedback insects per count.xlsx](https://github.com/NERC-CEH/fit-count-app/files/6124332/feedback.insects.per.count.xlsx)

**Comment by CCarvell** [comment]
Suggest a slight edit to the text:

"You counted X insects altogether - the UK average for [month] is Y insects per count."
