### ISSUE TITLE
Add How To page

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#35]
- [x] Remove current About page to Menu
- [x] Add How To page placeholder in the bottom tabs
- [x] Add bullet point texts

**Comment by kitenetter** [comment]
Text for 'how to' page:

[FIT Count quick guide text.zip](https://github.com/NERC-CEH/fit-count-app/files/6125400/FIT.Count.quick.guide.text.zip)

I've tried to make it as short as I can but let me know if you think it is still too long!

**Comment by kitenetter** [comment]
Sorry, minor edits, have deleted previous version:

[FIT Count quick guide text.zip](https://github.com/NERC-CEH/fit-count-app/files/6125430/FIT.Count.quick.guide.text.zip)
