### ISSUE TITLE
App registration - drop "how did you hear about" question?

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#37]
I know we've discussed this before, but this list is still problematic, because:
- The current list is out of date
- It will cause additional complications for translation and for multiple countries
- It adds to the length and complexity of the registation process, and is therefore a potential barrier to engagement

I would propose that we drop this question, and instead rely on seeking feedback from users who opt-in to receiving further communications from us, one of which could be a questionnaire that covers the issue of how they heard about PoMS.

@CCarvell do you agree that we can drop this question?

(The same question arises for the website as well.)

**Comment by DavidRoy** [comment]
I definitely agree on this

**Comment by CCarvell** [comment]
I agree to dropping the question. 
I had been working up the list of other organisations/ projects to add but starting to see the pitfalls myself. Had some dialogue with Matt Heard at National Trust - who want to use FIT Counts - but his answer was:
"I think from our point of view it’s most useful if the app had a tag for records on our land i.e. each count, the unwieldy bit. In terms of utility to benchmark this is potentially important ie unify data from many recorders. _At the moment we download and post process from irecord_ etc. Tab for NT probably more use to you guys than us for engagement understanding…"

@kitenetter where he says "at the moment we download and post process from irecord" does that mean they are downloading full raw FIT Count results of their own from the iRecord site? Do you know of others already doing this? 
Provided we can allow for downloads of user count data to csv from the website, as Martin has said should be possible (and those csv downloads do not need to be in Welsh) then groups and projects can analyse their own data as they wish.

**Comment by kitenetter** [comment]
@CCarvell NT do access species records from iRecord that fall within their land, but this does not include the PoMS data, which is not shared in this way.

We don't have a good answer to providing PoMS data for multiple landholdings but I think we had previously agreed that is outside the scope of current work.

**Comment by DavidRoy** [comment]
I agree that providing access to partners is a secondary question.  We 'could' do something like the iRecord-NT download but would need a bit of thinking through.

Maybe raise a separate issue for this under PoMs as it's not relevant to the app

**Comment by CCarvell** [comment]
Let's keep the 'partner/ group downloads' for a future phase. I was simply checking that individual users can access their own data, such that groups of individuals can, if they wish, come together to pool their counts if part of a project where they want to view a set of counts collectively (e.g. to compare with national averages or to compare between their own sites or years). Examples who may want to use the app to do this are:
Earthwatch
Buglife B lines
Pollinating London Together
Farmer Clusters/ Estates

**Comment by kazlauskis** [comment]
Thanks, we'll remove the question from the registration then.
