### ISSUE TITLE
Insect ID guide - changes to layout of text

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#38]
Species groups should be ordered in same way as in the survey:
Bumblebees - Honeybees
Solitary bees - Wasps
Hoverflies - Other flies
Butterflies and moths - Beetles
Small insects - Other insects

Edits needed to bring the bullet points to the top of each page (let me know if you want this in a spreadsheet instead):

**Bumblebees screen 1:**
Move text box to bottom.
Delete "Look out for:"
Remove "Description" subhead, just have two paragraphs of text

**Bumblebees screen 2:**
Remove "Description" subhead

**Honeybees screen 1:**
Move text box to bottom.
Delete "Look out for:"
Remove "Description" subhead, just have two paragraphs of text

**Honeybees screen 2:**
Remove "Description" subhead

**Solitary bees screen 1:**
Move text box to bottom.
Delete "Look out for:"
Remove "Description" subhead, just have two paragraphs of text
Edit number of species in final sentence to:
"There are about 250 species in the UK."

**Solitary bees screen 2:**
Remove "Description" subhead

**Solitary bees screen 3:**
Move text box to bottom.
Edit text paragraph to change first sentence and last sentence:
"Among the many species of solitary bee, there is a lot of variation in size, colour and how hairy they appear. Some examples are shown above."
Remove "Description" subhead, just have two paragraphs of text

**Wasps screen 1:**
Move text box to bottom.
Delete "Look out for:"

**Wasps screen 2:**
Move text box to bottom.
Remove "Description" subhead, just have two paragraphs of text

**Wasps screen 3:**
Move text box to bottom.
Edit final sentence of text paragraph to:
"Two examples are shown above."
Remove "Description" subhead, just have two paragraphs of text

**Hoverflies screen 1:**
Move text box to bottom.
Delete "Look out for:"
Remove "Description" subhead, just have two paragraphs of text

**Hoverflies screen 2:**
Move text box to bottom.

**Hoverflies screen 3:**
Move text box to bottom.
Edit text to:
"Many hoverflies have the typical black and yellow markings, but there is quite a lot of variety in shape, size and marking among the full range of species. Some examples are shown above."

**Other flies screen 1:**
Move text box to bottom.

**Other flies screen 2:**
Move text box to bottom.

**Butterflies and moths screen 1:**
Move text box to bottom.
Remove "Description" subhead, just have two paragraphs of text

**Butterflies and moths screen 2:**
Move text box to bottom.

**Beetles screen 1:**
Move text box to bottom.

**Beetles screen 2:**
Move text box to bottom.
Edit text to:
"Above are two more examples of beetles that regularly visit flowers."

**Small insects screen 1:**
Move text box to bottom.

**Other insects screen 1:**
Move text box to bottom.
Edit bullet 1 to:
"Other insects you may see include sawflies, which come in a variety of colours and sizes - some look rather like wasps"

**Other insects screen 2:**
Move text box to bottom.

**Comment by CCarvell** [comment]
Great work - agree with removing "Description" subheads etc. I am happy to approve all the insect ID guide pages.

Three small edits: 
1. Species names - some of the text includes species names but they are not showing in italics. eg. within Hoverflies, _Volucella zonaria_.  within Other flies _Chloromyia formosa_. Can you put species names in italics?

2. Typo in Hoverflies screen 2: correct "honybees" in "Drone-fly hoverflies have a much more hovering flight than honeybees,"
Also can we make the "And" in Butterflies and Moths with a small case "a"?

3. Page title currently reads "Insects" - can it change to "Insect Groups"?
