### ISSUE TITLE
Should we submit zero abundance occurrences?

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#39]
At the moment, we don't upload occurrences with 0 counts, should we instead upload those too?

**Comment by kitenetter** [comment]
On the website we don't store **occurrences** with zero counts - no occurrence is created unless an insect group has a count of >=1. It is not possible to enter a count of zero.

However, we definitely to want to store **samples** that have no occurrences, i.e. when no insects were seen at all.

**Comment by kazlauskis** [comment]
Great, thanks!
