### ISSUE TITLE
Target Flower list

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#4]
* [x] list
* [x] images
* [ ] texts

**Comment by kazlauskis** [comment]
@kitenetter is the UK list the one in the iRecord form? Also, where can we find the flower images for profiles and selecting species from the list?
<img width="379" alt="Screenshot 2021-01-20 at 18 55 10" src="https://user-images.githubusercontent.com/7383162/105221472-118f1380-5b51-11eb-8354-6da54bcf8548.png">

**Comment by kitenetter** [comment]
The list for UK use is as shown on the recording form:
- Dandelion
- Buttercup
- White Dead-nettle
- Hawthorn
- Bramble/Blackberry 
- Lavender (English)
- Common/Greater Knapweed
- Heather (Calluna or Erica)
- Hogweed
- White Clover
- Ragwort
- Thistle (Carduus or Cirsium)
- Buddleja 
- Ivy

If needed we could simplify some of those names:
- Dandelion
- Buttercup
- White Dead-nettle
- Hawthorn
- **Bramble**
- **Lavender**
- **Knapweed**
- **Heather**
- Hogweed
- White Clover
- Ragwort
- **Thistle**
- Buddleja 
- Ivy

Will sort out images next.

**Comment by kitenetter** [comment]
@kazlauskis I've just sent you a set of 14 photos for the target flowers, via the UKCEH file transfer system. I've cropped the photos square, but haven't standardised the sizes. Let me know if you need me to do any further editing.

Some of the photos are better than others so let me know if you think any of them are not suitable. Most are mine or Nadine's, but !'ve included two sourced from wikimedia that are under CC BY-SA licences. I think we can use these as long as we credit the photographers within the app, but let me know if you have any concerns. I have the info for the credits list.

**Comment by kazlauskis** [comment]
Great, thanks! 

@Vilius-Stankaitis I have put these in the shared folder.

**Comment by kazlauskis** [comment]
@CCarvell @kitenetter I can't remember if we have decided to add a full flower list guide into the 1st version of the app or should we skip it and just use the photos for the Target Flower page in the survey?

**Comment by kitenetter** [comment]
@kazlauskis the flower guide is a lower priority than the insect guide, and also requires more thought and re-working to make it suitable for within-app use. So I think all we can do at the moment is refer people to the online PDFs.

There are currently English and Welsh versions hosted on the UKCEH website, but the intention is to move them to the new PoMS website, but I don't yet know what the URL will be for the specific page.

At the moment all we can do is link to:
ukpoms.org.uk

**Comment by kazlauskis** [comment]
Thanks, I am closing this ticket then. We will remove the flower guide page and just leave the insect guide for this version. We can put the website link in the about/manual pages.
