### ISSUE TITLE
Record start time of FIT Count

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#40]
A quick question about the start time of each FIT Count (ie. time of day 11:30am when the count is conducted). This data is not entered by the app user, but is it recorded when the count is complete? Will the app retain the time the count was conducted, not the time it was uploaded when online?  sorry if this has already been covered.

**Comment by kazlauskis** [comment]
Yes, we do capture this automatically. When the user taps 'Start count' in a pre-count page then we capture the time of day and upload this alongside other survey attributes.
