### ISSUE TITLE
Edits to make the app less UK-specific: About and Credits

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#41]
Based on our discussion earlier.

The Word doc below has edited text for these two pages. I have made the text more generic, and have listed the projects that use the app on the "About" page, and the projects whose funder have funded the app on the "Credits" page. Those two lists are currently very similar but could change as more projects come on board. I have not listed individual funders.

[Page edits to remove UK focus.docx](https://github.com/NERC-CEH/fit-count-app/files/6165694/Page.edits.to.remove.UK.focus.docx)

There are some questions in the document for @CCarvell and/or @DavidRoy - please confirm whether you are happy with the text or wish to edit it further.

These two pages will then need to be re-translated.

On the "About" page I have given a contact link for people to contact the overall FIT Count project. That link os for the contact form on the FIT Count website;
https://fitcount.ceh.ac.uk/contact

That form is currently set to direct messages to the PoMS generic email, but at one point we had agreed that the FIT Count website should be linked to the BRC generic email, but either way the link will work.

**Comment by CCarvell** [comment]
@kitenetter really appreciate you picking this up - I have been in another meeting! I will take a look and comment this evening.

**Comment by kazlauskis** [comment]
Looks good from my perspective. I think you can use symbols like the info icon in the text.

**Comment by CCarvell** [comment]
I agree with Martin's excellent edits and have added a couple of minor Track changes here:
[Page.edits.to.remove.UK.focus_CC.docx](https://github.com/NERC-CEH/fit-count-app/files/6167784/Page.edits.to.remove.UK.focus_CC.docx)

Note that as inferred, point 2 in the i icon Quick Guide, may need to be changed for different countries with alternative seasons.
Here is the SURPASS logo.
![surpass_logo_3](https://user-images.githubusercontent.com/44494345/111712786-3f898f00-8846-11eb-95d7-b48902ad17de.png)
