### ISSUE TITLE
Link to Privacy notice and Terms of use

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#42]
- [x] The current link to the Privacy Notice goes to an incorrect URL (https://fitcount.ceh.ac.uk/privacy-policy). It should go to:
https://fitcount.ceh.ac.uk/privacy-notice
- [x] For Welsh users it should point to `https://fitcount.ceh.ac.uk/cy/privacy-notice` both in the registration page and the menu.
- [x] Ideally we should also give a link to the Terms of use:
https://fitcount.ceh.ac.uk/terms
- [x] For Welsh users it should point to `https://fitcount.ceh.ac.uk/cy/terms` both in the registration page and the menu.

**Comment by kazlauskis** [comment]
Thanks, we'll add the Terms link in the menu too.
