### ISSUE TITLE
Guidance for country-specific pollinator guides

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#43]
Questions for @kazlauskis 

If another country is producing an pollinator guide, they may wish to replace the photos we have used with photos of species from that country.

How much (if any) flexibility do they have with the numbered features? For instance, if the UK photo has five numbered points, will the Cyprus photo also have to have five numbered points?

If the UK guide has three photos of solitary bees, will the Cyprus guide have to have three photos of solitary bees?

There is UK specific text in the insect guide (e.g. it gives the number of UK species for some of the insect groups). I would rather not have to remove the UK information for UK use, and I am hoping that when translated the equivalent figures can be given for other countries - is that possible?

Some countries will need to have a different set of species groups - I don't think we can avoid this. This will affect the guides, but will also mean a different set of line-drawing buttons for the species groups (for use within the ID guide and for the survey count page). This is not an issue for Cyprus but will be for South America.

**Comment by kazlauskis** [comment]
In short, this is the complexity I am trying to avoid. That is, partially editing species profiles, which will complicate the setup a lot. This is kind of a bit technical but I think the best way forward would be to treat a species entity (profile) as a unit that could not be split up and partially changed for different countries. At the moment, a species entity consists of things like `internalID`, `warehouseID`, `commonName`,  `photos`, `annotations` etc. So if any of these had to be changed for a country then it is best to duplicate the whole entity (inc. the photos) to the exact same one but with a different `internalID` + change any country-specific info. In such a way we would have a bit of duplication but it would give full flexibility for our partners to create any species content and keep the set up easy to understand. What do you think?

The instructions for country-specific guides would be:
1. Try to reuse as many species profiles from the current app
2. If some profiles need a change then copy over the content and create new profiles
3. If totally new species are required then create new profiles
