### ISSUE TITLE
2nd Onboarding screen check for title showing on Beta version

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#46]
The 6-point FIT Count how-to page that is the second onboarding screen is cutting off the title on my iPhone 8 screen. Just see the bottom of the pink bold text.

**Comment by kazlauskis** [comment]
@CCarvell we have tried to reproduce this on various devices, including the iPhone 8, but no luck so far. Would it be possible for you to attach a screenshot of the page on your device? Also, do you have some accessibility settings changed in your device settings like font size increased or device resolution changed? Thanks!

**Comment by CCarvell** [comment]
@kazlauskis This was the screenshot I took when I downloaded the app and noticed the issue. I have font size enlarged due to an eye issue, so perhaps that's what has caused the issue. Please ignore if it doesn't seem important.
![onboarding](https://user-images.githubusercontent.com/44494345/112342249-f9a34f80-8cb9-11eb-886d-dd474a93efc5.png)

**Comment by kazlauskis** [comment]
Ah, thanks! We have now pushed a fix that should improve this.
