### ISSUE TITLE
replacement login email

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/fit-count-app#47]
currently comes from vilius@flumens.io

@kitenetter do we have a fitcount@ceh.ac.uk email - which is probably the most appropriate?

**Comment by kitenetter** [comment]
We don't have a fitcount@ address, I thought we had agreed that the brc@ address would be used. The alternative would be the poms@ address.

Do you want me to request a new fitcoutn@ address (I think there's an embargo on doing this until the email system has been switched over).

I'm inclined to use brc or poms if we can, simply to avoid having yet another email box to have to keep checking.

**Comment by kazlauskis** [comment]
Shall we do the `poms@` email then?

**Comment by kazlauskis** [comment]
I have changed it to`poms@ceh.ac.uk` now. Reopen this if you wanted it to be anything else.
