### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/fit-count-app#48]
Can't login to the FIT Count app, even after reset of email.  I can login to https://fitcount.ceh.ac.uk/ ok

**Comment by kazlauskis** [comment]
Try it again now, the account username has diverged from the email so you weren't able to log in. We have a task to fix this before the public release.

**Comment by DavidRoy** [comment]
thanks, is the username needed for login?

**Comment by kazlauskis** [comment]
Yes, the authentication spec requires it to be a username so app login matches it with email. We will be changing this so that it is more robust and the authentication would be using the email instead - users will be able to set any username which we won't use in authentication.
