### ISSUE TITLE
Placename search on map page?

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/fit-count-app#49]
It would help to have a placename search on the map to help locate sample location

**Comment by kitenetter** [comment]
I agree that a placename and/or postcode search would be useful if possible.

@kazlauskis I think you said that we could adjust the zoom level at which the location becomes accepted. If so, I think we should make the threshold one level lower (or is it higher?) than it currently is - i.e. so you don't have to zoom in quite so far. Hopefully if we allow one more level we'll still get a reasonably precise location (the current level of zoom-in seems to produce a very precise location, more precise than we need).

**Comment by kazlauskis** [comment]
Yes, we could add this in.

I can see that iRecord forms use [OSM geocoding](https://operations.osmfoundation.org/policies/nominatim/), with its limitations it isn't really good for apps, do you have some other existing [geocoding](https://gisgeography.com/geocoders/) service we could use for this? 

We're currently using Mapbox mapping tiles in the apps, it also has a geocoding service with [100K/month requests being free](https://www.mapbox.com/pricing/#search).

**Comment by DavidRoy** [comment]
Mapbox seems a good option.  I doubt we'd get high usage as most people will rely on GPS location?

**Comment by kazlauskis** [comment]
Thanks, we'll start the work on the placename search then.

**Comment by kazlauskis** [comment]
When the user selects a suggested placename I assume you don't want to auto-select the centroid location of the place only zoom-in to the selected area, is that correct?

**Comment by kitenetter** [comment]
Correct.

**Comment by kazlauskis** [comment]
I've added the placename search, it shows the search results based on your country (and precise location) and tapping a result zooms to the place on the map.
