### ISSUE TITLE
Arrow at bottom of insect page?

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/fit-count-app#51]
On the insect count page, count there be a downward facing arrow on the first page to show that there are more insect categories on the second page.  The two dots are helpful but subtle.

Or maybe just a guide on first use of the page?

**Comment by kazlauskis** [comment]
Thanks, we'll improve this.

**Comment by kazlauskis** [comment]
We've done this now. Made the list continuous but still sticky, so the species should appear in the same positions between the swipes. 

Here is how it looks now (temporarily added blue and green to show different slides)


https://user-images.githubusercontent.com/7383162/112642396-2d59b300-8e3b-11eb-9a94-e31b3c54730a.mov
