### ISSUE TITLE
Count does not upload

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/fit-count-app#52]
@kazlauskis I've completed a count but it does not upload.  I have a good connection.
It just shows the survey page with the 'upload' button.

Should there be a message if upload is unsuccessful?

Tried at 18:16 on 21/3/21 if you want to check the logs.

**Comment by kazlauskis** [comment]
Thanks, we'll look into this.

**Comment by kazlauskis** [comment]
@DavidRoy could you please try to upload your survey again now?

**Comment by DavidRoy** [comment]
success :-)

**Comment by kazlauskis** [comment]
Yay 🎉 The reason you couldn't upload is that the account was created through the website rather than the app.

@BirenRathod do you know if it is possible to disable the user registration on the FIT Count website?

**Comment by BirenRathod** [comment]
@kazlauskis I have disabled the user registration form.
@DavidRoy I have enabled the Captcha, so it will stop creating spam user.

**Comment by kazlauskis** [comment]
@BirenRathod it looks like the registration was disabled for mobile users as well, could you please only disable this for the website - may be just hiding the registration page form rather than disable it fully. Thanks

**Comment by BirenRathod** [comment]
@kazlauskis I have implemented the settings now, can you check if it is working fine?

**Comment by kazlauskis** [comment]
Thanks Biren, the app registration is working now.
