### ISSUE TITLE
website logo

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/fit-count-app#54]
@BirenRathod

Can you add this logo to https://fitcount.ceh.ac.uk/ replacing the default drupal logo

![FitCountLogo](https://user-images.githubusercontent.com/2699478/111986392-cddf6880-8b05-11eb-847b-7d8f3126f86e.jpg)

**Comment by BirenRathod** [comment]
@DavidRoy Logo has been added now.

**Comment by kazlauskis** [comment]
The website shows the new logo so I am closing this.
