### ISSUE TITLE
Allow the "Other" flower name to be skipped?

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#55]
At the moment, if you select "Other" as your target flower, you have to type in a name for the species, under the heading "I know the species"

1. Suggest that we change from "I know the species" to "Please add the name of the flower".
2. It isn't obvious that this is a mandatory field; hopefully the above re-wording will help explain this, but I wonder if it is possible to provide an option for "unknown" at this point.

This is one of the few parts of the app where the user has to type in text. And since we know that many FIT Count participants do use "other" flowers it is likely to be required quite frequently.

So there is a case for trying to make this simpler for the user to skip through if they don't know the flower name.

However, there are also downsides to this, in that if we make is easy to skip through we may find that most users do exactly that, in which case we will lose the ability to classify "other" flowers into their families, unless we spend time determining them from photos.

I would suggest that we action point 1 above immediately, but keep point 2 as an option to apply later on if we get feedback that people are struggling with the mandatory flower name.

**Comment by kazlauskis** [comment]
Thanks, we'll change the wording. In the future, it would be easy to add an 'unknown' option to the list too.

**Comment by kazlauskis** [comment]
@Vilius-Stankaitis can you please add the `(required)` to the mentioned heading - like we're doing it now for other pages.
