### ISSUE TITLE
PoMS-Ky logo not displaying correctly

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#57]
On the [app demo](https://fit.app.flumens.io/demo.html) credits page, the PoMS-Ky logo is missing the flower for the "o":

![image](https://user-images.githubusercontent.com/16039111/112484644-07b4a700-8d72-11eb-8413-6732de43ae00.png)

**Comment by Vilius-Stankaitis** [comment]
Hi, if you could give me one, I will change it

**Comment by kitenetter** [comment]
New versions of the PoMS-Ky logo here:

[PoMSKy_new_logos.zip](https://github.com/NERC-CEH/fit-count-app/files/6207283/PoMSKy_new_logos.zip)
