### ISSUE TITLE
Survey doesn't upload

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#61]
I carried out a test survey at the weekend. I was away from wifi and also had mobile data switched off.

At the end of the survey I asked the app to upload the survey, just to see what happened. It tried to upload but failed, as expected, and the survey remained in the pending list.

However, when I came back within wifi range the survey is still failing to upload. No error message is given, it just tries to upload for a few seconds, then stops, and leaves the survey in the pending list.

**Comment by kazlauskis** [comment]
@kitenetter try it again now.

**Comment by kitenetter** [comment]
Thanks @kazlauskis that has uploaded and I can see it on the test version of the new PoMS website.

**Comment by kazlauskis** [comment]
@johnvanbreda do you know if calling `index.php/services/user_identifier/get_user_id` from a Drupal website automatically attaches that user's account to the calling site in the warehouse? What has happened here is that Martin had an account in the Warehouse linked to multiple sites, upon app registration the Indicia API module has fetched the existing warehouse ID for Martin's drupal-profile but the warehouse hasn't added the drupal site to the warehouse-profile account. So when the app is uploading records to the warehouse (using JWT), the warehouse doesn't find the user account linked to the site and so the warehouse rejects the submission. It works OK for new user accounts though.

**Comment by johnvanbreda** [comment]
@kazlauskis yes, it should do that. If it didn't automatically link existing accounts to the website it would not be possible to link 1 account to more than 1 website. Can you create a test case?

**Comment by kazlauskis** [comment]
Thanks, this has only happened to Martin and David. Since they are both 'super-users' on the warehouse and also admins on the site I will leave this ticket closed for now. I will reopen the ticket and delve deeper into this if any regular users encounter this issue.

**Comment by kitenetter** [comment]
I've had a report of a survey not uploading from a standard user who has just downloaded the test app (iOS version), registered as a new user and tried to submit a count. He doesn't give much detail, but it sounds similar to the problem I had:
"I couldn’t upload my fictitious results, but I guess that’s because it’s a test version."

**Comment by kitenetter** [comment]
This appears to be linked to a registration problem so is not the same problem that I was experiencing.

**Comment by kazlauskis** [comment]
Yes, the user has to verify the email before uploading any surveys.

**Comment by DavidRoy** [comment]
Is there a way to give this status within the app?  This is likely to catch out others?

**Comment by kitenetter** [comment]
The user says he did not receive an email.

**Comment by DavidRoy** [comment]
I think there is a Spam filter issue?
@birenrathod

**Comment by kazlauskis** [comment]
In the app, we ask to confirm the email after the registration as well as when trying to upload the first survey and we can rephrase the messages to make them clearer. Essentially this comes down to finding the verification email and clicking on the verification link.

**Comment by DavidRoy** [comment]
@kazlauskis can you make the message specific to the stage of registration, e.g. '...you still need to verify you account by clicking on the link in an email sent from xxx@ceh.ac.uk..'

**Comment by kitenetter** [comment]
Our test user confirms that the registration email ended up in his spam folder. If there's anything we can do to make this less likely to happen that would be good. Should we add a warning to users that they may need to check their spam folder?

**Comment by DavidRoy** [comment]
I'll add a separate issue about options for reducing the likelihood of getting caught up in spam filters and tracking registration status.  
@kitenetter please close this issue if appropriate

**Comment by BirenRathod** [comment]
@DavidRoy, @kazlauskis & @kitenetter 
I have configured the email service, so it will no longer end up in spam.
