### ISSUE TITLE
How to test the apple version of the app

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#62]
@kazlauskis one of our contacts is trying to test the app on an Apple dvice. He has gone to the link you gave:
- For Apple devices (iPhones, iPads): https://testflight.apple.com/join/aVHilgCx

And now has the 'testflight' installed, but doesn't know how to link this to the FIT Count app.

**Comment by kazlauskis** [comment]
### Installation
To get started, install TestFlight on the device you’ll use for testing. Then, follow the public link invitation to install the beta app. 

1. Install TestFlight on the iOS device that you’ll use for testing.
2. Tap on the public link on your iOS device.
3. Tap View in TestFlight or Start Testing; or tap Install or Update for the app you want to test.

**Comment by kitenetter** [comment]
Our tester says:
OK – I’ve installed Testflight again on my iPhone. I get a message saying I have no apps available to test.
What is a ‘public link’ and where do I find it?

**Comment by kazlauskis** [comment]
The link is the one in the Beta email above: https://testflight.apple.com/join/aVHilgCx

**Comment by kitenetter** [comment]
Sorry Karolis, neither I nor our tester are understanding this.

On the testflight web page it says "tap on the public link on your iOS device". Where is the public link, do you access it from the testflight app, or is it somewhere else in the phone?

If it is in the app, where do you find it?

Can you send us a screenshot?

**Comment by kazlauskis** [comment]
The link should be opened in any browser on the device, the default one is Safari. This is the link they should open in the browser: https://testflight.apple.com/join/aVHilgCx

If the person has that link somewhere in an email (from you or others) then tapping on it in the email should be enough.

The link should automatically launch the TestFlight app where they can proceed with the FIT App installation. In case the link doesn't open the TestFlight app then tap **Start Testing** link in the page from the above link .

**Comment by kitenetter** [comment]
Thanks @kazlauskis - in the end our tester was able to download the app. Closing.
