### ISSUE TITLE
Option to reduce likelihood of registration emails getting treated as spam

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/fit-count-app#63]
@birenrathod to advice on options for reducing the likelihood of emails with a link to confirm registration getting caught by spam filters

**Comment by BirenRathod** [comment]
@DavidRoy This has resolved now as mentioned in #61

**Comment by DavidRoy** [comment]
Thanks Biren.  Please can you configure all sites to avoid Spam in future.
