### ISSUE TITLE
Improve messaging of registration status

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/fit-count-app#64]
Provide warning message to users who haven't confirmed registration via link in email sent when creating an account

see NERC-CEH/fit-count-app#61 NERC-CEH/fit-count-app#63

**Comment by kazlauskis** [comment]
Is this ticket about extending the current message with _"...you still need to verify your account by clicking on the link in an email sent from xxx@ceh.ac.uk.."_?
