### ISSUE TITLE
Re-direct link to UKCEH PoMS webpages until new PoMS site is active?

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#67]
Both links in the app that go to the UKPoMS website (from the i page at the bottom for more info, and within the About page) are showing no page as the site is not launched yet.
Can we re-direct from the app to the current UKCEH PoMS pages with all guidance materials IF the app launches before the new website?

**Comment by kazlauskis** [comment]
Yes, though it would be better to keep the same link to the site in the app but add a redirect to the website until it is set up. This way you won't need to push a new app update once the site is working and the URL link would remain constant.

**Comment by CCarvell** [comment]
@kitenetter I think this will be an action for Biren which we would be doing anyway to redirect to the current guidance until the website is active?

**Comment by kitenetter** [comment]
Agreed. Will raise this as an issue on the website pages. Closing here.
