### ISSUE TITLE
Uploaded surveys and clarity on how to view your data

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#68]
Uploaded surveys are just listed by date, but you can't click in the app and view these to remind yourself of what you saw or what your target flowers were etc.
I can't remember if we have put a sentence in the app to explain how a user can view their count data - via the PoMS website user account (ideally)? or via the FIT Count website? Does it come up in the final message after you complete a survey? Some further clarity on this would be good.

**Comment by kazlauskis** [comment]
Sure, one option would be to show a message if a user taps on an uploaded record in the list. What would you like to say to the user?

**Comment by CCarvell** [comment]
@kitenetter can you help advise on this? may depend on what will show in the new website, but of course this will be different for other non-PoMS projects. Can we say
"View your FIT Count data via the relevant project website (eg. PoMS in UK)"? or just leave it as is with survey, date and number of insects counted in Uploaded surveys?

**Comment by kazlauskis** [comment]
The text would be shown to all countries but it can be translated differently in other languages. As long as the 'format' of the translations remain the same then translators are free to modify the text.

**Comment by kitenetter** [comment]
Okay. We can't guarantee an exact match between choice of language and country in which surveys take place, so I think something similar to Claire's suggested text will work:

      To view your FIT Count data after uploading please visit the project website for your country, where available (e.g. UK PoMS)

If we can include a hyperlink this should be:
(e.g. [UK PoMS](http://ukpoms.org.uk/))

@kazlauskis will you add this to transifex or shall I ask Elen for a translation via email?

**Comment by kazlauskis** [comment]
@kitenetter I have added this to the app, see attached pic. The translations are now in Transifex and I have emailed Elen too. Do you want me to wait until the Welsh translation is done before we release the app?

<img width="349" alt="Screenshot 2021-04-23 at 09 11 50" src="https://user-images.githubusercontent.com/7383162/115841908-2e1f3e00-a415-11eb-98ae-926fc5404ec1.png">

**Comment by CCarvell** [comment]
@kazlauskis perfect thank you.
This is a minor addition - if Elen responds this morning then great - we can have the Welsh done before first release - but if we are nearly there with all other issues then I would really like to push ahead and get the app to the 2 app stores for approval today.
