### ISSUE TITLE
Do we have any options for allowing location details to be added when data is not available?

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#69]
Feedback from Richard Dawson:
It is not possible to view a map without wi-fi / mobile data active / connected which may be an issue in some locations. Without being able to see the map there does not appear to be any way to enter a location, although I assume that the GPS will still function even if the map background cannot be displayed.

Is there a way to input the location later on or manually? If you can’t enter location the app won’t progress to actually do a FiT Count.

I think this could be a concern for promoting FiT Counts where I do the RSPB engagement as there is limited mobile signal at the ‘picnic area’ and it could prevent undertaking FiT Counts via the app at ‘remote locations’ once it is linked to the 1km squares.

**Comment by CCarvell** [comment]
@kazlauskis if a user is NOT connected to mobile data or wifi, will they still be able to type in their location (eg. place name or post code) in the search box? I understand that they may have to pinpoint the exact location on the map on return to base or signal.
@kitenetter if you think this DOES require a text edit in the Read More box (despite my note in the other issue) can we make this TODAY - Thursday? 
@kazlauskis would it be accurate to add this text?
"If you do not have internet signal, enter a location name and return to the map later when uploading your count".

**Comment by kazlauskis** [comment]
No, the location search only works where there is a network connection. This location name is not saved and is only used for locating yourself within the map when you have a connection. I would say to leave it as it is, the GPS is the primary way to find the current location.

**Comment by kitenetter** [comment]
This may be too late to change for the first version, but I would suggest changing the Help text at the top of the map page to read:
Enable your GPS to set your location, or use the map to zoom in and tap on your location

And in the "Read more" text, the final paragraph could be:
If your GPS is switched on your location should already be set, but if not please zoom in to find the spot that best matches your location.

I don't think this is critical to change for the first release.

**Comment by CCarvell** [comment]
Follow up of dialogue on this from 10/05: Martin's @kitenetter suggested edits above still a good idea, but with possible extra clarification of what to do when you are offline:

I think we need to add a sentence for clarity to the READ MORE Info page that links from the survey page 1 (location). Can this be done with a simple update?
I don’t know what the GPS button is, and also can’t find on my own phone where to see that GPS is turned on!
 
I suggest adding something like this AFTER “Please zoom in to find the spot that best matches your location” and before “Your count results…..” but will need technical correction as this may not be right:
 
“Make sure you have the GPS location function on your device switched on. If you are conducting a FIT Count offline or without network connection, the app will not find your location on the map, but your GPS should record this for uploading later”???
We should accept that this might not be translated ASAP, or perhaps Ellen would be happy to do this one sentence into Welsh for us asap?
 
Also perhaps once Martin has a developer account set up to reply to user reviews, we could add a note to the response from that first query about functionality when offline?

**Comment by kazlauskis** [comment]
Do the screenshot and a slightly reworded phrase look OK? These both would require translations, do you want to contact the translators or should I push this? 

### READ MORE

  <p>
                Your location can be anywhere where there are flowers to attract
                pollinating insects, where you have permission to be, and where
                it is safe to go.
              </p>
              <p>
                A garden or park, farm or nature reserve are all great locations
                for FIT Counts.
              </p>
              <p>
                Please zoom in to find the spot that best matches your location.
              </p>
              <p>
                Make sure you have the GPS turned on and permissions granted. If
                you are conducting a FIT Count offline or without a network
                connection, the app will not find your location on the map, but
                your GPS should record this for uploading later.
              </p>
              <p>
                Your count results will be visible to others at the 1 km square
                level via the UKPoMS website.
              </p>

<img width="341" alt="Screenshot 2021-05-10 at 21 16 48" src="https://user-images.githubusercontent.com/7383162/117719400-4644da80-b1d5-11eb-829b-3b2134e39d01.png">

**Comment by kazlauskis** [comment]
OK, I will write to Elen, do you want me to wait for her to finish the translations first or should I push this update to the app stores without that?

**Comment by kitenetter** [comment]
Hi @kazlauskis - @CCarvell and I have discussed this again this morning and I've been checking how the app works on my phone without a data/wifi signal, and for me at least the GPS is functioning as expected, and an accurate location is being captured. However, it is not very obvious to the user that this is happening.

We would like to update things before the website launch on 20 May, which I think means we do have time to get the wording translated by Elen, and we would like to go ahead with the wording changes as shown above.

In addition, is it possible to implement any of these other options:
- Add a box above the map that displays a UK grid ref if the location is in the UK, or a lat/long elsewhere, so that the user is reassured that a location has been captured (i.e. same functionality as used for iRecord Butterflies and European Ladybirds etc.)
- Add a box above the map that allows the user to add an optional free text place name
- If a user starts the survey with their GPS switched off, is it possible to enable a pop-up that requests the user turn on the GPS?

If any of those above options can be implemented by 20 May that would be great, otherwise they can go on the features list for the next update.

While testing the various apps this morning to check how the GPS function was performing, it was apparent that in some cases the apps take much longer than others to pick up a GPS location. In some cases it took several minutes of 'egg-timer' before a location was found, while in others it happened quite quickly. Is there anything within the app that can be optimised to reduce the waiting time, or does it depend entirely on the phone and perhaps the satellite availability?

**Comment by CCarvell** [comment]
@karolis as you were going to return to this in June - I am just putting out a reminder to all.

From discussions with @JimChiazzese1 and SURPASS team it is likely that they would want to include the option listed above:
**Add a box above the map that allows the user to add an optional free text place name**

This would help users who may be without signal or unable to store the GPS location of their count or see the correct place on the map. It could be essential if an offline user was conducting multiple FIT Counts at different locations on the same day?
Is it possible to get this into Transifex, or is it already there?

**Comment by JimChiazzese1** [comment]
@kazlauskis @CCarvell Just a comment on the freeform location box. I assume it will possible to flag this field was used before the user submits the survey (when back on a connection). i.e if submitting a survey that only has a text box location description and not an actual mapped location can the user be prevented from submitting the survey and get a prompt that they have to verify the location correctly?
Apologies if that's already been discussed in the past.

**Comment by kazlauskis** [comment]
The location name is merely a search field that works only when there is a network connection. The location name is discarded after the user navigates away from the page. To navigate to the step 2, the app has to geolocate the device or the user has to select some location on the map so the user can't skip the step 1 without setting some valid location to the survey.

**Comment by JimChiazzese1** [comment]
@kazlauskis Sorry Karolis, I think my question probably confused things - it was really just me thinking aloud about possible functionality.

I'll wait until you comment on Claire's previous question - lack of signal/inability to use GPS etc seemed to be an issue that the S.American teams are keen to have a work around for.

**Comment by kazlauskis** [comment]
> Just a comment on the freeform location box. I assume it will possible to flag this field was used before the user submits the survey (when back on a connection). i.e if submitting a survey that only has a text box location description and not an actual mapped location can the user be prevented from submitting the survey and get a prompt that they have to verify the location correctly?

We can reuse the same location search input field as a survey location-name. The app could save whatever was entered in that field for upload to the warehouse then. If the app is online then this field would also suggest possible locations as well as zoom in on the map to that location. If offline, then this would simply be a location-name field.

At the moment, it isn't possible to navigate to step 2 without a valid location set. We could remove this restriction for progressing through the survey but ask the user to enter the location before uploading.

We could also show selected location coordinates/gridref somewhere on that page and possibly allow to edit this manually.

**Comment by JimChiazzese1** [comment]
_"One idea would be to add a ‘Skip’ button to the location page so that the user can progress the survey pages whilst in the field and add the location information at home before uploading the survey. There would also have to be some sort of reminder to set the location manually in the app"_

I think that would work perfectly. User gets the option to skip if location not working and then is prevented from submitting the survey/receives a prompt if there is no location on the survey and adds it manually by using the map function.
@CCarvell - I think this is what we discussed previously as the best solution?
While most users, most of the time should have functioning GPS, they might not have location settings properly enabled or know how to do that and if also no network then they won't be able to select from the map. With the above solution, no-one is prevented from undertaking any survey due to GPS, network, technical knowledge, whilst in the field.

**Comment by JimChiazzese1** [comment]
@kazlauskis @CCarvell Just to pick this up again - Is it possible to implement this functionality and if so, at what stage should it be done. 
One other refinement is to allow the user to add text so they can easily identify the survey when adding the location when back online before submitting.
So workflow becomes:
- No GPS or mapping available
- User 'skips' or selects to enter location later
- User presented with a location related text box to add details of where they are "eg Bottom of Tom's field"
- User conducts survey
- When back online, user goes to submit, receives prompt that location is missing
- User manually navigates map to add location. 
- Add location, submit survey

**Comment by kazlauskis** [comment]
We've done this one now.

This is how it used to look like for offline users:

![localhost_8000_survey_new_83660777-7fdf-4371-8ff5-74de8772d60c_location(iPhone SE (2020))](https://user-images.githubusercontent.com/7383162/181505986-e6124db7-e182-4383-9069-1df174c1ed07.png)

It looks like this now:

![localhost_8000_survey_new_3dc69647-19ac-4fba-b0f1-98508d01ad04_location(iPhone SE (2020)) (1)](https://user-images.githubusercontent.com/7383162/181506142-e7ff302e-6111-4754-ba39-e12654c93432.png)

![localhost_8000_survey_new_3dc69647-19ac-4fba-b0f1-98508d01ad04_location(iPhone SE (2020))](https://user-images.githubusercontent.com/7383162/181506175-fa7171ae-1b69-41f8-b002-ad1a1abf3172.png)

If the location isn't entered then the user can also enter the current site name:

![localhost_8000_survey_new_4fbd6d06-4738-417e-8649-68366784594a_location-name(iPhone SE (2020))](https://user-images.githubusercontent.com/7383162/181506265-7dc9bd4b-a348-43e5-920f-039941f37e53.png)


This has created a bunch of new interface terms that are now uploaded to Transifex for translations.

**Comment by JimChiazzese1** [comment]
Thanks Karolis. Including @CCarvell  on this as well.

To clarify then; If the user can't use the maps they can enter just GPS...if they can't do that either they can just add a location name.
Couple of questions:

1. Do we have any text that informs the user that if they can't use GPS or maps then they can enter a name and then update the location details at a later date when they submit the count.
2. If they try and submit a count without the location data are they stopped and prompted for the location data?

On point 1 I can suggest some text if needed. 

Thanks

Jim

**Comment by kazlauskis** [comment]
1. The only text that helps the user with this scenario is in the screenshots.
2. Yes, the app won't allow to upload records without a valid location and will notify the user to fill it in if missing.

**Comment by JimChiazzese1** [comment]
Great. Thanks Karolis
