### ISSUE TITLE
Find location by postcode

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#70]
The map search function does not allow searching by postcide - could this be added?

**Comment by kitenetter** [comment]
May be complex for non-UK locations?

**Comment by kazlauskis** [comment]
Yes, I can enable the postcode search.

**Comment by CCarvell** [comment]
@kitenetter I have discussed this with Karolis - we decided it would be OK for him to enable a postcode search within the 'Search for a location' box without us having to make any edits to the Info behind the READ MORE box on the location screen.

There was also the point from Richard Dawson to "add warning about GPS use" from the team meeting, but this would involve translation edits and so perhaps we can see how things go with user feedback and address this for next version if it's a real problem?

@kazlauskis to enable postcode search within the 'Search for a location' box
