### ISSUE TITLE
FIT Count website - contact form

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#73]
If you send a message to the FIT Count website, e.g. from https://fitcount.ceh.ac.uk/contact, the message is currently being sent to Claire. Can we set all message to go to the PoMS email address (user ID 49)?

Action for @BirenRathod (I don't seem to be able to assign you).

**Comment by kitenetter** [comment]
@kazlauskis can you link Biren in to this please

**Comment by BirenRathod** [comment]
@kitenetter I have amended the email address to the one used by user id 49.

**Comment by kazlauskis** [comment]
@kitenetter I have given you extra permissions to the repo. Let me know if you still can't assign people to issues.

**Comment by BirenRathod** [comment]
@kazlauskis It is same for me too. I can't assign to him as well.

**Comment by kazlauskis** [comment]
@BirenRathod added you too now.

**Comment by BirenRathod** [comment]
Thanks, @kazlauskis

**Comment by kitenetter** [comment]
Just tried to test the contact form on the website and got an error:

![image](https://user-images.githubusercontent.com/16039111/115791555-8710b700-a3c0-11eb-842f-844d6e95f6af.png)

I ticked the box to send a copy of the test email to my own address, and that has arrived, but no email has arrived in the poms@ceh.ac.uk inbox.

**Comment by BirenRathod** [comment]
@kitenetter I didn't see the error message. I have sent three emails, so check if you receive in poms@ceh.ac.uk inbox. they all got my email address.

**Comment by kitenetter** [comment]
@BirenRathod Your three messages have arrived in the PoMS inbox, but I've tried to use the contact form again myself and I'm still getting the error message. I'm logged in as https://fitcount.ceh.ac.uk/user/35

**Comment by BirenRathod** [comment]
@kitenetter That should not be a problem. The messages I sent, one of them using same admin role as your one and others sent without login. I just sent you another message by masquerading as you and found no problem. Can you check poms inbox and see if you see the message.

**Comment by kitenetter** [comment]
Yes I can see the one that you have sent from my account. So it looks like this is just a problem for me.

**Comment by BirenRathod** [comment]
@kitenetter yes, that's right. May be you can try again after clearing cookies from your browser.

**Comment by kitenetter** [comment]
WIll do. Closing.
