### ISSUE TITLE
Removing “PoMS” from 'other flies' text and replace with "FIT Counts"

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#75]
Minor edit from Team meeting that will NOT involve any translation.
Within the pollinator groups ID guide, 'Other flies' in the paragraph below the 6 features, replace the word "PoMS" with "FIT Counts".
@kitenetter to update this on the Outlook Excel sheet in English - and make sure the Welsh version updates as well (but no translation requirement)

**Comment by kitenetter** [comment]
@CCarvell sorry, not sure what you mean by "Outlook Excel sheet"?

**Comment by kazlauskis** [comment]
@kitenetter sorry, we have a shared doc where we keep all the species lists, annotations, habitats etc. I thought you had access to it, I have just sent you an invitation.

**Comment by kitenetter** [comment]
In the shared doc for English text I have replaced "PoMS" with "the FIT Count" in two places:
- other_flies_1, into text
- butterflies and moths 1, extra text

What do I need to do to update the Welsh text?

**Comment by kazlauskis** [comment]
@kitenetter the translations are in Transifex, do you have access to the Welsh there?

**Comment by kazlauskis** [comment]
I've pulled in the new texts and updated the Welsh translations (replaced "PoMS" with "Fit Count").
