### ISSUE TITLE
Web links on FIT Count website home page

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#76]
For info @CCarvell @DavidRoy

I have added links from the FIT Count website to the country-specific PoMS pages:
https://fitcount.ceh.ac.uk/home

and have asked Elen to translate the sentence explaining what the links are.

We can add further country links as they become available.

If you are happy with this please close the issue.

**Comment by CCarvell** [comment]
I am happy thanks - will see if I can close the issue!

**Comment by CCarvell** [comment]
@kitenetter sorry I can't see how to close an issue so can you do this?

**Comment by kazlauskis** [comment]
@CCarvell I have resent an invitation for you to join the GitHub project as an admin.
