### ISSUE TITLE
Users blocked

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#78]
We've had a few users get in touch to say they haven't received the registration confirmation email. On the FIT Count website I can see that they are blocked.

Do new accounts always get shown as blocked until the user confirms their registration?

Can I unblock them, or is there a way of re-sending the confirmation email?

**Comment by BirenRathod** [comment]
@kitenetter Please unblock them. Also, I have updated library to support email execution system. That should resolve the registration confirmation email.

Yes, new accounts always get shown blocked until the user confirms their registration.

**Comment by kitenetter** [comment]
If I unblock them, how do they set their password, will they be asked to do that when they log in?

**Comment by BirenRathod** [comment]
@kitenetter Actually they do not need to set their password as they must have got at the time of created. if they don't remember then they can use forgot password feature.

**Comment by kitenetter** [comment]
I've unblocked the account for the user who got in touch. It seems to have saved okay but I got this error message:

![image](https://user-images.githubusercontent.com/16039111/117307839-d652ef00-ae78-11eb-8183-7c13012e5c89.png)

Should I unblock **_all_** the blocked accounts (there are about 20 that have registered since the app was launched)?

**Comment by BirenRathod** [comment]
@kitenetter yes, that is fine. Yes, this warning message do come up sometime but it will be resolved in due time.

**Comment by kitenetter** [comment]
I did a bulk activation of all the blocked emails, and got this error:
"The application did not respond in time."

However, they do now all seem to be active.

Closing.

**Comment by kitenetter** [comment]
@BirenRathod 
We still seem to be ending up with a lot of blocked user registrations. Currently we have over 150 active users, and about 40 blocked users. I can't see any obvious reason why some users are getting blocked.

Two questions:
1. What causes a user account to be marked as "blocked"?
2. Should I just unblock all the blocked ones, or could that result in spam users getting through?

**Comment by BirenRathod** [comment]
@kitenetter 

1. Generally if user failed to response from notification email received after registering on site then their account got blocked.  All though, I checked logs and I haven't found any failed email notifications, so there is only one possibility which mentioned here.
2. you can unblock all users if they look genuine.

**Comment by DavidRoy** [comment]
@BirenRathod is there anything we can do to minimise the likelihood of registration link emails getting caught up by spam filters?
@kazlauskis anything we can do in the app to alert users to their registration status?

**Comment by kazlauskis** [comment]
We ask the user to verify the account at the time of registration and also when the user is trying to upload a record with an unverified account. Having some accounts blocked isn't a bad thing in itself. We simply allow the users to explore the app without requiring them to verify the account first, which means that some users will decide to not verify their account at all and not upload any data or delete the app altogether if it isn't something they have expected. 

Another way would be to force the verification before continuing with the app. 

One improvement in the app would be the ability to resend the verification email.

**Comment by DavidRoy** [comment]
Agreed.  
I would support any improvements for this process to be handled via the app, e.g. add the ability to resend the verification email.

**Comment by kitenetter** [comment]
I don't if there is anything more we can do on this, but at the moment we are getting more blocked registrations than active ones:

![image](https://user-images.githubusercontent.com/16039111/120452006-d23bc380-c389-11eb-8636-e15c74a65193.png)

**Comment by DavidRoy** [comment]
I think the best option is to embed messages in the app to show registration status to users.  @kazlauskis has recently implemented this for the ButterflyCount app

**Comment by CCarvell** [comment]
@kitenetter @kazlauskis have we solved the issue of blocked registrations?
I am concerned about people getting put off at this stage.
We have just asked NI to push for promotion (they have already been doing this) and will be promoting the app during Defra's Bees Needs week w/c 12th July to would be good to know if this glitch can be solved. thanks

**Comment by kitenetter** [comment]
Looking at registrations over the last week and a bit I estimate that about half are showing as blocked, so this is still a problem.

I don't think we've had any recent emails complaining about being unable to register, which is a bit odd, and perhaps indicates that people are giving up if it doesn't work first time?

**Comment by CCarvell** [comment]
I just checked the App store and there are no bad reviews appearing as a result of people reporting registration issues.
But I am concerned about losing peoples' interest, especially if these are people who are unlikely to go and print off forms to enter counts via the website.
@BirenRathod said you can unblock all users if they look genuine.
And have we tried to minimise the likelihood of registration link emails getting caught up by spam filters?

**Comment by kitenetter** [comment]
For what it is worth, I just got round to registering my home email address for the FIT Count app, and the process work absolutely smoothly - the email arrived immediately in my inbox, it reads clearly, I clicked the link and my account is now active.

It's very difficult to know why it is failing for so many others.

I will do another bulk unblocking, but that will result in some mis-typed emails being set to active, and may result in some spam emails being registered (I can't preview the full email addresses before unblocking unless I open up each account one at a time).

**Comment by kazlauskis** [comment]
From the app's perspective, it might not be a problem that half the users ignore the verification step - some might not be interested in uploading the data. I personally don't verify my account if I find I don't want to proceed with using some product features that require that - losing the interest might be a bigger issue here. Of course it is definitely a problem if the users that want to upload the surveys don't receive the emails.

**Comment by kitenetter** [comment]
@kazlauskis I'm sure you're right that some of the blocked accounts will be from people who decided not to proceed, but I did recognise a few of the blocked accounts and they included people who are active recorders and I am pretty sure do want to be using the app and contributing to PoMS.

**Comment by CCarvell** [comment]
Thanks both. I agree that we do not want to artificially enable those who are not genuine users to have registered accounts. But it is very hard to separate those (I hope they are fewer) from potential genuine users.

**Comment by kitenetter** [comment]
Have not seen any recent problems. Closing.
