### ISSUE TITLE
Enable android Back button

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#79]
A user writes:
"Just installed the app. Got as far as Start Survey screen and wanted to then exit. Back button (android, Samsung S9+)  has no effect, I had to use other means to close it. Standard behaviour is for the back button to exit an app if you are on first screen."

Is there a reason why the back button doesn't allow the app to be exited?

**Comment by kazlauskis** [comment]
Did the **Home** button in the header not work? The android back button is disabled intentionally so that it doesn't mess up with the custom navigation here.

<img width="389" alt="Screenshot 2021-05-06 at 12 56 54" src="https://user-images.githubusercontent.com/7383162/117294427-8a00b280-ae6a-11eb-93ed-a515b2bec937.png">

**Comment by kitenetter** [comment]
On my phone, the Home button works, but having got to the Home page I can't get out of the app via the back button, I have to open the app manager list and close it from there. Most of my other apps close via the back button, which I think is what this user was trying to do.

**Comment by kazlauskis** [comment]
@kitenetter do you have this bar on your device? Have you tried the circle?

<img width="621" alt="Screenshot 2021-05-06 at 17 00 05" src="https://user-images.githubusercontent.com/7383162/117329392-84b45f80-ae8c-11eb-86fb-1c3c6a2879c1.png">

**Comment by kitenetter** [comment]
No, I have a list button on the left:

![image](https://user-images.githubusercontent.com/16039111/117330875-09ec4400-ae8e-11eb-8da0-fcc856fc627d.png)

and a back button on the right:

![image](https://user-images.githubusercontent.com/16039111/117330763-ede8a280-ae8d-11eb-9d30-ba3ce1fed92a.png)

with a home button (a physical button rather than a touchscreen button) in the middle.

I don't know what options the user has, but I got the impression he was trying to use the back button to come out of the app, which as I say is what I do for most apps but it doesn't work for the Indicia-related ones.

I don't think this is worth spending a lot of time on, I just wondered if there was a reason why the back button doesn't work for our apps, and it may be what you said earlier about it being disabled to prevent things going wrong in mid-survey.

**Comment by kazlauskis** [comment]
Thanks, I agree, we should fix it at some point. This was raised in other apps and we'll just need to prioritize this.

**Comment by kitenetter** [comment]
For info, we've had another complaint about being unable to exit the app - the user thought they had to shut their phone down completely in order to close the app. I guess they aren't familiar with the app manager options.
