### ISSUE TITLE
Insect group illustrations

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#8]
We will be using illustrations from [here](http://plantecology.webs7.uvigo.es/iconos-de-grupos-funcionales-de-polinizadores/), but some of UK groups are missing or requires clarification:

species |  note
-- | -- 
Bumblebees  | 
Honeybees | ❌
Solitary bees | Which one?
Wasps |   
Hoverflies |  Which one?
Other flies |  ❌
Butterflies and moths |  Butterfly or moth?
Beetles | Which one?
Small insects (<3mm) | ❌
Other insects |  ❌

**Comment by kazlauskis** [comment]
@kitenetter Do you know where to find the illustrations for the missing ones?

**Comment by kitenetter** [comment]
Here is a file containing an illustration for each of the PoMS insect groups:
[insect line drawings.zip](https://github.com/NERC-CEH/fit-count-app/files/5874062/insect.line.drawings.zip)

Most of these come from Divulgare:
http://plantecology.webs7.uvigo.es/iconos-de-grupos-funcionales-de-polinizadores/

The two exceptions are for Honeybee and Aphid (which is what we use to ilustrate "Other insects"), which have been sourced from alternative copyright free sources. See the READ ME files for details.

Divulgare also provide illustrations of bird, reptile and mammal pollinators that may be of use for projects outside the UK.
