### ISSUE TITLE
Spelling correction on Wasps ID page

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#80]
In the Wasps ID page, point 3 has a spelling error:
bold **back** 
should say
bold **black** 
@kazlauskis can you correct this directly with the next update, then it will appear correctly for the Cyprus version too?

**Comment by kazlauskis** [comment]
Thanks, I've done this now. This text lives in the shared excel document so you should be able to make these tweaks to the descriptions there yourselves.
