### ISSUE TITLE
Cyprus Actions from team meeting

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#81]

**Comment by CCarvell** [comment]
Copy of email with Actions for Cyprus - as the team are not all on GitHub we will probably have to deal with these by email but I am just logging this here:
These are the Actions I noted (a couple of extra ones since I checked the translation document again FIT Count- App_Cyprus (14.05.21) ), please add others if I have missed anything:
1.	Karolis to specify the country choice as “Cyprus” (vs “UK”) and language choices as “English” or “Greek” 
2.	Karolis to correct Transifex English for point 2 on the i info page with “FIT Count quick guide” – the translation should be correct but Ioanna to check below
You can complete a FIT Count in good weather at any time of year. = Οι μετρήσεις FIT μπορούν να πραγματοποιηθούν καθ’όλη τη διάρκεια του χρόνου, όταν ο καιρός είναι καλός, όποτε βρίσκετε ανθοφόρα φυτά.

3.	Marius to provide insect species photos for species listed and highlighted in the attached word document, p. 18 onwards and check where the species name has been changed in the English text. Can you check if you have the Hornet Hoverfly and confirm what you want to do about that one? Please upload photos clearly named with the species to the Google drive shared by Ioanna
4.	Ioanna/ Kelly to check text for the English where it refers to number of species in UK/ Cyprus – see Claire’s edits in the attached doc from p. 17. Claire to add to photos tab in Species_data.xls (note if this is too complicated then we will have to remove these points about number of species per country for the next country version).
5.	Karolis to send photo requirements to all for a) flower photo square dimensions and b) insect photo dimensions
6.	Claire to select best target flower photos from google drive folder and save on P drive for re-sizing – check with Helen for support?
7.	Ioanna/ Marius to add final missing flower photo – Chrysanthemum? To google drive folder
8.	Ioanna/ Marius to provide any extra names for photo credits on the Credits page – email to Karolis
9.	Ioanna/ Kelly to add flower type categories to the list of target flowers on p. 9-10 of the attached doc. – then Claire to add categories to Species_data.xls
10.	Ioanna/ Kelly to confirm how you would like the user feedback message to appear. The UK wording “average for April is 4 insects per count” comes from a data table we provided to Karolis with the average total number of insects counted in each month on all UK FIT counts from previous years. If you want this feedback message in Cyprus, please clarify which numbers you would like added and check translation.
You counted 3 insect(s) altogether- the UK average for April is 4 insects per count.= Μετρήσατε συνολικά 3 έντομα - ο μέσος όρος της Κύπρου για τον Απρίλιο είναι …. έντομα ανά μέτρηση.

11.	Kelly to confirm email address for the app to send Feedback queries to from the link in the About page (currently website feedback from the app goes to the UKpoms email account but Cyprus feedback should go to Kelly’s team). I do not think we need to edit that text at the bottom of the About page but appreciate that some technical questions could still end up going to Kelly’s team which would need to come back to Karolis!
12.	Ioanna to check changes in English text on the About page, this is now worded to be more global since you took the screenshots for translation, see comments in attached on p. 28 and edit in Transifex if needed
13.	 Jodey to coordinate with Kelly and John/ Andy van Breda regarding data Warehouse and transfer to PoMS-Ky database (data will be safe within the main FIT Count indicia warehouse initially)
14.	Kelly are you happy with the Privacy notice and Terms and Conditions which sit on the FIT Count website? – are we assuming these will not be translated? I’m OK with that, but we do have them in Welsh.
15.	Claire and Kelly/ Ioanna to discuss longer term maintenance and running of FIT Counts with David Roy and Helen (linked with new EU PoMS project and Horizon 2020): Claire to set up a meeting once EUPoMS is underway

**Comment by CCarvell** [comment]
Update on Actions 18/06/2021

2. Separate issue raised and labelled - sorry!

3. Claire to check photos and sizing on Google shared folder - Ioanna meeting Pantelis next week to check again if we can find some more photos for final examples -  if they cannot find examples of all the insect photos for species from Cyprus, then agreed to keep the UK examples but add a very short note to the translation in Transifex saying “(example species from the UK)”

3 and 4. Claire to add new text to photos tab in Species_data.xls and add new insect IDs where needed

6. Claire to add two new target flowers and photos to the Google sheet and then notify Andy van Breda and Martin to add the new Warehouse IDs
7. Done - flower photos all complete - Claire to check SIZING to be square as per instructions
8. Sort final photo credits once final full set is agreed
9. Claire to take category types from Word doc and enter to Google sheet

10. User feedback - Ioanna says "We don’t have the average total number of insects counted in each month yet. " 
@kazlauskis can the user feedback message for Cyprus say just "Thank you....you counted X insects"? Do you need to edit the Transifex site for this?

**Comment by kazlauskis** [comment]
@CCarvell regards the 10,  I have now added a new term to Transifex that would require the translation.

**Comment by CCarvell** [comment]
@kazlauskis this is the list of names to appear under the Credits for photos from the Cyprus team:


•	Marios Philippou
•	Pantelis Charilaou
•	Graham Johnstone
•	Kelly Martinou
•	Ioanna Angelidou
•	Varnava J. Andri
•	Jakovos Demetriou
•	David Navrátil & 8K postprocessing M.Hoskovec

if we do this on the main global Credits page for every country, the list will become very long. 
Will it be better to have photo credits listed separately for each country?

**Comment by kazlauskis** [comment]
Sure, I can show this in Cyprus only. Do you want to translate the 'postprocessing' or should we keep it in English only?
