### ISSUE TITLE
Credits page edit

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#83]
@kazlauskis as agreed with the team, please can you add the following to the Credits page of the app, I suggest putting it under the Graphics: section after FIT Count logo and before Photos:

App design concepts: Francisco E. Fontúrbel (Pontificia Universidad Católica de Valparaíso)

**Comment by CCarvell** [comment]
@kazlauskis could you update us on this - has it been added yet? I think I have updated the app on my phone but this edit is not appearing in the Credits yet.

**Comment by kazlauskis** [comment]
No, I haven't yet. Even for a trivial update like this, re-uploading the app has some overheads so I was hoping to bundle it up with the Cyprus update. Let me know if I shouldn't wait for it and update it instead.
