### ISSUE TITLE
Tagging Jim Chiazzese for SURPASS work

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#84]
@kazlauskis you added Jim to the repo on 21/05 but I cannot seem to tag him?

Please can you explain or tag Jim's account name?

**Comment by kazlauskis** [comment]
He hasn't yet accepted the invitation.

**Comment by JimChiazzese1** [comment]
I think the invitation may have come through prior to me having a github account? So that when trying to accept the invite I was prompted to first set up an account, which meant the original invite wasn't actually accepted? Could that be the reason I can't be tagged? @kazlauskis @CCarvell

**Comment by kazlauskis** [comment]
Yes, that's probably the case, I've resent the invite now.

**Comment by JimChiazzese1** [comment]
Thanks @kazlauskis That's sorted it now. Jim
