### ISSUE TITLE
Point 2 on the i info page with “FIT Count quick guide” 

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#85]
For Cyprus, we need to edit text under point 2 on the i info app page with “FIT Count quick guide”:

You can complete a FIT Count in good weather at any time of year.

Οι μετρήσεις FIT μπορούν να πραγματοποιηθούν καθ’όλη τη διάρκεια του χρόνου, όταν ο καιρός είναι καλός, σε ανθοφόρα φυτά

@kazlauskis I think this needs a new English entry in Transifex for us to add the Greek - is that something you can do please, including add the Greek from above?

**Comment by kazlauskis** [comment]
Added the term and the translation.
