### ISSUE TITLE
Translation of Privacy Policy and Terms & Conditions 

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#86]
Re: the app Privacy Policy and Terms and Conditions that are hosted on the FIT Count website and not on the app -  https://fitcount.ceh.ac.uk/

@kitenetter or @kazlauskis do you know which part of Transifex was used to do the Welsh translation for the UK version?

We need to confirm that the current text is suitable for Cyprus and then the S American countries, and then decide where to post that text for translation.

@kitenetter @BirenRathod to keep you up to date, we have agreed (with David) to create separate country pages for each of the three S American countries within the FIT website (so that will increase in content) as they do not currently have project websites like UK PoMS or PoMSKy. 

@JimChiazzese1 will be supporting the process for S America and liaising with our 3 country leads there.

**Comment by kitenetter** [comment]
The privacy and terms are on transifex here:
https://www.transifex.com/ceh/fitcount-website/content/

**Comment by CCarvell** [comment]
@JimChiazzese1 after our discussion today, see above that Martin notes the privacy and terms text is on Transifex. If you could still review it and check it's fit for purpose for Brazil etc - they could then have the option to slightly modify the wording in their translation - except that would be OK for Portuguese and Brazil, but the Spanish version would have to agree between Chile and Arg.

**Comment by JimChiazzese1** [comment]
Thanks for the links @kitenetter I see now I was searching within the app part of Transifex and not the separate website section. I'll request Portuguese is added to that and have the Brazil team translate, after reviewing appropriateness with them.

**Comment by JimChiazzese1** [comment]
@kazlauskis Can you please give me permissions on transifex for the FitCount website so that I can invite translators. I've also requested Portuguese to be added as a language. Thanks Jim

**Comment by kazlauskis** [comment]
@JimChiazzese1 I have now added you to the website maintainers list.

**Comment by kitenetter** [comment]
Not all languages have yet translated the terms and privacy, but I don't think there is any further action to take for this issue. Closing.
