### ISSUE TITLE
ID guide Wasps page 1 - typo to correct

### ISSUE THREAD

**Issue by CCarvell** [NERC-CEH/fit-count-app#87]
@kazlauskis in the ID guide, page 1 of the Wasps group has a typo for the word black:

Point 3
"have bold back and yellow stripes"

should say
"have bold black and yellow stripes"

**Comment by kazlauskis** [comment]
This text should be updated in our shared excel document. I can pull these changes into the app once you've corrected these. @JimChiazzese1 @kitenetter

**Comment by JimChiazzese1** [comment]
@kazlauskis Can I just verify how this process should work please? Claire's found an issue on the app itself, so assume the process is locate the typo/issue on the species spreadsheet on https://flumensio.sharepoint.com/ update on there and inform via Github, you then re-import to fix the issue. 
Out of interest, do you reimport the whole sheet or just the area impacted and does that happen each time an issue is reported or at fixed release stages? Looking at the spread sheet (If it is the one on your sharepoint), it does look like it's been updated from 'back' to 'black' already.
Thanks
Jim
