### ISSUE TITLE
Query over uploading results

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#94]
This user has an active account on the FIT Count website, but is unable to upload results:

> According to your app I have successfully logged on. However, I have been
> trying to upload my survey all afternoon without success. I have clicked
> “upload” the wheel icon starts turning but it doesn’t upload. Can you
> advise please?

Is there any action we can suggest? I guess it may be a problem with their internet connectivity?

**Comment by DavidRoy** [comment]
I notice there are a lot of blocked accounts again on https://fitcount.ceh.ac.uk/
@BirenRathod can you check there is no issue with emails being sent from this site

@kazlauskis as this is a D8 site, can we use the newer user authentication approach to indicate 'within-in' for registration status?

**Comment by BirenRathod** [comment]
@DavidRoy, @kazlauskis I don't see any errors of not sending emails. The only possible reason is that those users haven't been signed in back to activate their account.

**Comment by kazlauskis** [comment]
@kitenetter I would need the Drupal user ID, login timestamp and the app version to investigate this further, is it possible to find this out?

@DavidRoy yes, we've got two tickets related to this #64 #82. We can do both just haven't prioritised this yet.

**Comment by kitenetter** [comment]
@kazlauskis the Drupal user ID is 836, and I can ask them for the app version (I'm pretty sure they will have downloaded it in the last few days, and they registered three days ago). How do I find the login timestamp?

I've just noticed that in their email (at 27/07/2021 22:44) they are labelled as "not verified", but they had accessed the website prior to that, according to the "Last access" in the website people table. Not sure what the significance of "not verified" is.

**Comment by kitenetter** [comment]
User ID 836 has now been able to upload their counts. Not quite sure what happened but it sounds like the user got muddled over their passwords. Closing.
