### ISSUE TITLE
Display user emails in the people table on the FIT Count website

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#95]
Is it possible to display the full email address in the people table here:
https://fitcount.ceh.ac.uk/admin/people

This could be done either by making the full username visible, or by adding an extra column for the email address.

This would make it easier to see whether accounts are blocked because the email address has been mis-typed, or for some other reason.

**Comment by BirenRathod** [comment]
@kitenetter I have added an email address column, so you can see whole email address.

**Comment by kitenetter** [comment]
Thanks
