### ISSUE TITLE
Failure to upload

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/fit-count-app#97]
I did a FIT Count yesterday that is showing as Pending on my phone. When I tap Upload it tries to do so for about a second but nothing happens - the survey won't upload, and there is no error message.

Is there anything I can do to find out why it isn't working, and to make it work?

**Comment by kazlauskis** [comment]
We'll have a look at this asap.

**Comment by kazlauskis** [comment]
[https://fitcount.ceh.ac.uk](https://fitcount.ceh.ac.uk) site SSL certificate is broken which prevents the users to login/register or upload the data. @BirenRathod could you please have a look at this?

**Comment by BirenRathod** [comment]
@kazlauskis No broken certificate found. It works fine. It might need to clear the cache if somebody have open during the site migration.

**Comment by BirenRathod** [comment]
@kazlauskis Although, fitcount has got same problem of registering as duenscapes got eventhough it has got updated with your latest code.

**Comment by kazlauskis** [comment]
Oh, is the FIT site Drupal 9 now? if so then what day was it upgraded?

**Comment by BirenRathod** [comment]
@kazlauskis yes, it is. just yesterday.

**Comment by kazlauskis** [comment]
Thanks, the upload issue might not be related to this then.

**Comment by BirenRathod** [comment]
@kazlauskis of course not. that is before I migrated on Drupal 9.

**Comment by kazlauskis** [comment]
@BirenRathod there is an issue with DP9 authentication. For some reason the same refresh token works in https://live-ceh-fitcount.pantheonsite.io but doesn't work in https://fitcount.ceh.ac.uk, any ideas why?

**Comment by kazlauskis** [comment]
@kitenetter I am trying to understand better where your issue lies but, at the moment, all the users that have logged in to the app before yesterday are probably affected with a similar problem. 

There is something that would be good to try with your app. Could you please re-login and upload the survey? Like this:

1. logout (uncheck 'Discard local data' so you don't loose the surveys)
2. re-login again 
3. upload the survey
4. if failed then just note the time of upload

**Comment by kazlauskis** [comment]
@BirenRathod can you please give me access to the new site on Pantheon so I can have a look at the modules?

**Comment by BirenRathod** [comment]
> @BirenRathod there is an issue with DP9 authentication. For some reason the same refresh token works in https://live-ceh-fitcount.pantheonsite.io but doesn't work in https://fitcount.ceh.ac.uk, any ideas why?

@kazlauskis I didn't find any dissimilarity in both sites. I have added you on new site now.

**Comment by kazlauskis** [comment]
Thanks. Yeah, I don't know why current user sessions aren't recognised in the new site. I will check the code now.

**Comment by kitenetter** [comment]
@kazlauskis I logged out and back in, and have just tried the upload (at 2.45pm according to my phone), and the wheel went round for a little longer than before, but it still has not uploaded.

Tried again a fraction before 2.47pm but same result.

**Comment by kazlauskis** [comment]
Thanks a lot, we are working on this with Biren at the moment. I'll check the logs if there is something new I can pick.

**Comment by kazlauskis** [comment]
Thanks again for the re-upload. I guess you are a Beta tester and I have find an issue that is very much linked to the Cyprus update. I have now fixed it and pushed the app update, it might take a day or so to reach you but, fingers crossed, your upload should be fixed now. This fix will be in the app v1.0.4 (88), please reopen the ticket if you find this still an issue after the update.

**Comment by kitenetter** [comment]
The app updated yesterday and my count has now uploaded - thanks.
