### ISSUE TITLE
Country specific credit pages

### ISSUE THREAD

**Issue by JimChiazzese1** [NERC-CEH/fit-count-app#98]
@kazlauskis    My understanding (from looking at Transifex) is that the credits page is uniform across all the individual country versions of the app, however the names listed for photos credits are county specific - is that correct?
Please can you verify for me the preferred process for sharing the photo/image credits, as seems not via the spreadsheet.
Thanks
Jim

**Comment by kazlauskis** [comment]
Yes, the page is generic for all the languages/countries apart from the photo credits. You can create a ticket with the list of people you'd like us to show for any specific country and we'll update this in the code.

**Comment by JimChiazzese1** [comment]
Perfect - thanks Karolis. There's a chance that page could get very busy, very quickly. 
Brazil alone have 14 different photo credits for their flower images, so I wonder if there's consideration for making that page country specific as we go forward?

**Comment by kazlauskis** [comment]
Yeah, no problem, we can make the whole page country-specific. Another option would be to collapse the credits section so that it doesn't take so much space until expanded.
