### ISSUE TITLE
Previous user sessions no longer recognised

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/fit-count-app#99]
All previous user sessions for some reason are rejected from the upgraded Drupal 9 site. This means all users have to re-login to start uploading the data again.

**Comment by kazlauskis** [comment]
@BirenRathod I know you have pushed some fixes to the simple_oauth module which is good but something else seems still wrong as the previous refresh tokens are rejected by the new site. Do you know what else could be wrong?

**Comment by kazlauskis** [comment]
@BirenRathod could you upgrade the module to the latest version (5.0.4?) in the dev environment?

**Comment by BirenRathod** [comment]
@kazlauskis I have upgraded to its latest version.

**Comment by BirenRathod** [comment]
> @BirenRathod I know you have pushed some fixes to the simple_oauth module which is good but something else seems still wrong as the previous refresh tokens are rejected by the new site. Do you know what else could be wrong?

The only error, it produces is this -> User notice: Key file "file:///files/private/public.key" permissions are not correct, recommend changing to 600 or 660 instead of 770 in League\OAuth2\Server\CryptKey->__construct() (line 80 of /code/vendor/league/oauth2-server/src/CryptKey.php)
